"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import WorkspaceSectionSidebar from "../../WorkspaceSectionSidebar";
import AssetPicker,{type ProjectAsset} from "../../AssetPicker";

type NoteImage={id:string;assetId:string;caption:string;position:number;url:string};
type WorldNote={id:string;name:string;aliases:string;category:string;summary:string;details:string;significance:string;notes:string;position:number;images:NoteImage[]};
type CharacterOption={id:string;name:string;role:string;portraitUrl:string|null};
type LocationOption={id:string;name:string;type:string;region:string;imageUrl:string|null};
type CharacterLink={id:string;worldNoteId:string;characterId:string;label:string;notes:string};
type LocationLink={id:string;worldNoteId:string;locationId:string;label:string;notes:string};
type NoteRelation={id:string;sourceId:string;targetId:string;label:string;notes:string};
type SaveState="saved"|"saving"|"error";
const categories=["Faction","Culture","Religion","Magic","Creature","Object / Artifact","Historical Event","Technology","Organisation","Language / Terminology","Lore"];
const editable=(note:WorldNote)=>({name:note.name,aliases:note.aliases,category:note.category,summary:note.summary,details:note.details,significance:note.significance,notes:note.notes});
const snap=(note:WorldNote)=>JSON.stringify(editable(note));
const ordered=(images:NoteImage[])=>[...images].sort((a,b)=>a.position-b.position);
function initials(name:string){return name.trim().split(/\s+/).slice(0,2).map(part=>part[0]?.toUpperCase()).join("")||"?"}
function Field({label,value,onChange,placeholder,large=false}:{label:string;value:string;onChange:(value:string)=>void;placeholder:string;large?:boolean}){return <label className={large?"character-field character-field-large":"character-field"}><span>{label}</span><textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}

export default function WorldNotesBible({username,novel,initialNotes,characters,locations,initialCharacterLinks,initialLocationLinks,initialRelations}:{username:string;novel:{id:string;title:string};initialNotes:WorldNote[];characters:CharacterOption[];locations:LocationOption[];initialCharacterLinks:CharacterLink[];initialLocationLinks:LocationLink[];initialRelations:NoteRelation[]}){
  const [notes,setNotes]=useState(initialNotes),[activeId,setActiveId]=useState(initialNotes[0]?.id??""),[queryText,setQueryText]=useState(""),[categoryFilter,setCategoryFilter]=useState(""),[save,setSave]=useState<SaveState>("saved"),[navOpen,setNavOpen]=useState(false),[deleting,setDeleting]=useState(false),[deletePhrase,setDeletePhrase]=useState(""),[assetPickerOpen,setAssetPickerOpen]=useState(false),[imageError,setImageError]=useState("");
  const [characterLinks,setCharacterLinks]=useState(initialCharacterLinks),[locationLinks,setLocationLinks]=useState(initialLocationLinks),[relations,setRelations]=useState(initialRelations);
  const [addKind,setAddKind]=useState<"character"|"location"|"note"|null>(null),[linkTarget,setLinkTarget]=useState(""),[linkLabel,setLinkLabel]=useState("Associated"),[linkNotes,setLinkNotes]=useState(""),[linkError,setLinkError]=useState("");
  const notesRef=useRef(initialNotes),activeRef=useRef(activeId),timers=useRef(new Map<string,ReturnType<typeof setTimeout>>()),saved=useRef(new Map(initialNotes.map(note=>[note.id,snap(note)]))),seq=useRef(new Map<string,number>());
  const active=notes.find(note=>note.id===activeId)??notes[0],activeImages=ordered(active?.images??[]),primaryImage=activeImages[0];
  const activeCharacterLinks=active?characterLinks.filter(link=>link.worldNoteId===active.id):[],activeLocationLinks=active?locationLinks.filter(link=>link.worldNoteId===active.id):[],activeRelations=active?relations.filter(link=>link.sourceId===active.id||link.targetId===active.id):[];
  useEffect(()=>{notesRef.current=notes},[notes]);useEffect(()=>{activeRef.current=activeId},[activeId]);

  async function persist(note:WorldNote,keepalive=false){const body=snap(note);if(saved.current.get(note.id)===body)return true;const n=(seq.current.get(note.id)??0)+1;seq.current.set(note.id,n);setSave("saving");try{const response=await fetch(`/api/world-notes/${note.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(editable(note)),keepalive});if(!response.ok)throw new Error();if(seq.current.get(note.id)===n){saved.current.set(note.id,body);setSave("saved")}return true}catch{if(seq.current.get(note.id)===n)setSave("error");return false}}
  function schedule(note:WorldNote){const old=timers.current.get(note.id);if(old)clearTimeout(old);setSave("saving");timers.current.set(note.id,setTimeout(()=>{timers.current.delete(note.id);void persist(note)},650))}
  function update(patch:Partial<WorldNote>){setNotes(list=>list.map(note=>{if(note.id!==activeRef.current)return note;const next={...note,...patch};schedule(next);return next}))}
  function updateImages(noteId:string,fn:(images:NoteImage[])=>NoteImage[]){setNotes(list=>list.map(note=>note.id===noteId?{...note,images:fn(note.images)}:note))}
  async function select(id:string){const current=notesRef.current.find(note=>note.id===activeRef.current);if(current&&current.id!==id){const timer=timers.current.get(current.id);if(timer){clearTimeout(timer);timers.current.delete(current.id)}await persist(current)}setActiveId(id);setImageError("");setAddKind(null);setLinkError("")}
  async function addWorldNote(){const current=notesRef.current.find(note=>note.id===activeRef.current);if(current)await persist(current);const response=await fetch("/api/world-notes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({novelId:novel.id,category:categoryFilter||"Lore"})});if(!response.ok)return;const raw=await response.json();const note={...raw,images:[]} as WorldNote;saved.current.set(note.id,snap(note));setNotes(value=>[...value,note]);setActiveId(note.id);setQueryText("");setTimeout(()=>document.querySelector<HTMLInputElement>(".world-note-name")?.select(),30)}
  async function deleteWorldNote(){if(!active||deletePhrase!=="DELETE")return;const timer=timers.current.get(active.id);if(timer){clearTimeout(timer);timers.current.delete(active.id)}const doomed=active.id,response=await fetch(`/api/world-notes/${doomed}`,{method:"DELETE"});if(!response.ok)return;const index=notes.findIndex(note=>note.id===doomed),next=notes.filter(note=>note.id!==doomed);saved.current.delete(doomed);seq.current.delete(doomed);setNotes(next);notesRef.current=next;setCharacterLinks(list=>list.filter(link=>link.worldNoteId!==doomed));setLocationLinks(list=>list.filter(link=>link.worldNoteId!==doomed));setRelations(list=>list.filter(link=>link.sourceId!==doomed&&link.targetId!==doomed));setActiveId(next[Math.max(0,index-1)]?.id??next[0]?.id??"");setDeleting(false);setDeletePhrase("")}
  async function saveBeforeNavigate(){const current=notesRef.current.find(note=>note.id===activeRef.current);if(current){const timer=timers.current.get(current.id);if(timer){clearTimeout(timer);timers.current.delete(current.id)}await persist(current)}}
  useEffect(()=>{const flush=()=>{for(const timer of timers.current.values())clearTimeout(timer);timers.current.clear();for(const note of notesRef.current)if(saved.current.get(note.id)!==snap(note))void persist(note,true)};const visibility=()=>{if(document.visibilityState==="hidden")flush()};window.addEventListener("pagehide",flush);document.addEventListener("visibilitychange",visibility);return()=>{window.removeEventListener("pagehide",flush);document.removeEventListener("visibilitychange",visibility)}},[]);

  async function attachAsset(asset:ProjectAsset){if(!active)return;setAssetPickerOpen(false);setImageError("");const response=await fetch(`/api/world-notes/${active.id}/images`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({assetId:asset.id})});if(!response.ok){setImageError("The image could not be attached to this world note.");return}const image=await response.json() as NoteImage;updateImages(active.id,images=>images.some(item=>item.id===image.id)?images:[...images,image])}
  async function saveCaption(image:NoteImage,caption:string){if(!active)return;updateImages(active.id,images=>images.map(item=>item.id===image.id?{...item,caption}:item));await fetch(`/api/world-notes/${active.id}/images/${image.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({caption})})}
  async function makePrimary(image:NoteImage){if(!active)return;const response=await fetch(`/api/world-notes/${active.id}/images/${image.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({caption:image.caption,makePrimary:true})});if(!response.ok)return;updateImages(active.id,images=>{const rest=images.filter(item=>item.id!==image.id).sort((a,b)=>a.position-b.position).map((item,index)=>({...item,position:index+1}));return [{...image,position:0},...rest]})}
  async function removeImage(image:NoteImage){if(!active||!confirm("Remove this image from the world note? The project asset itself will be kept."))return;const response=await fetch(`/api/world-notes/${active.id}/images/${image.id}`,{method:"DELETE"});if(response.ok)updateImages(active.id,images=>images.filter(item=>item.id!==image.id).map((item,index)=>({...item,position:index})))}

  function beginLink(kind:"character"|"location"|"note"){
    if(!active)return;setAddKind(kind);setLinkLabel(kind==="note"?"Related":"Associated");setLinkNotes("");setLinkError("");
    if(kind==="character")setLinkTarget(characters.find(item=>!activeCharacterLinks.some(link=>link.characterId===item.id))?.id??"");
    if(kind==="location")setLinkTarget(locations.find(item=>!activeLocationLinks.some(link=>link.locationId===item.id))?.id??"");
    if(kind==="note")setLinkTarget(notes.find(item=>item.id!==active.id&&!activeRelations.some(link=>link.sourceId===item.id||link.targetId===item.id))?.id??"");
  }
  async function addLink(){
    if(!active||!addKind||!linkTarget)return;setLinkError("");
    const path=addKind==="character"?`/api/world-notes/${active.id}/characters`:addKind==="location"?`/api/world-notes/${active.id}/locations`:`/api/world-notes/${active.id}/relations`;
    const targetKey=addKind==="character"?"characterId":addKind==="location"?"locationId":"targetId";
    const response=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({[targetKey]:linkTarget,label:linkLabel,notes:linkNotes})});
    const data=await response.json().catch(()=>({error:"Link could not be added."}));if(!response.ok){setLinkError(data.error||"Link could not be added.");return}
    if(addKind==="character")setCharacterLinks(list=>[...list,data as CharacterLink]);else if(addKind==="location")setLocationLinks(list=>[...list,data as LocationLink]);else setRelations(list=>[...list,data as NoteRelation]);setAddKind(null);
  }
  async function saveCharacterLink(link:CharacterLink,patch:Partial<Pick<CharacterLink,"label"|"notes">>){const next={...link,...patch};setCharacterLinks(list=>list.map(item=>item.id===link.id?next:item));await fetch(`/api/world-notes/${link.worldNoteId}/characters/${link.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({label:next.label,notes:next.notes})})}
  async function saveLocationLink(link:LocationLink,patch:Partial<Pick<LocationLink,"label"|"notes">>){const next={...link,...patch};setLocationLinks(list=>list.map(item=>item.id===link.id?next:item));await fetch(`/api/world-notes/${link.worldNoteId}/locations/${link.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({label:next.label,notes:next.notes})})}
  async function saveRelation(link:NoteRelation,patch:Partial<Pick<NoteRelation,"label"|"notes">>){if(!active)return;const next={...link,...patch};setRelations(list=>list.map(item=>item.id===link.id?next:item));await fetch(`/api/world-notes/${active.id}/relations/${link.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({label:next.label,notes:next.notes})})}
  async function removeLink(kind:"character"|"location"|"note",id:string){if(!active||!confirm("Remove this connection? The linked profile will be kept."))return;const path=kind==="character"?`/api/world-notes/${active.id}/characters/${id}`:kind==="location"?`/api/world-notes/${active.id}/locations/${id}`:`/api/world-notes/${active.id}/relations/${id}`;const response=await fetch(path,{method:"DELETE"});if(!response.ok)return;if(kind==="character")setCharacterLinks(list=>list.filter(item=>item.id!==id));else if(kind==="location")setLocationLinks(list=>list.filter(item=>item.id!==id));else setRelations(list=>list.filter(item=>item.id!==id))}

  const categoryChoices=useMemo(()=>[...new Set([...categories,...notes.map(note=>note.category).filter(Boolean)])].sort((a,b)=>a.localeCompare(b)),[notes]);
  const filtered=useMemo(()=>{const q=queryText.trim().toLowerCase();return notes.filter(note=>(!categoryFilter||note.category===categoryFilter)&&(!q||[note.name,note.aliases,note.category,note.summary].some(value=>value.toLowerCase().includes(q))))},[notes,queryText,categoryFilter]);
  const availableCharacters=characters.filter(item=>!activeCharacterLinks.some(link=>link.characterId===item.id)),availableLocations=locations.filter(item=>!activeLocationLinks.some(link=>link.locationId===item.id)),availableNotes=active?notes.filter(item=>item.id!==active.id&&!activeRelations.some(link=>link.sourceId===item.id||link.targetId===item.id)):[];
  return <div className="app section-shell"><WorkspaceSectionSidebar username={username} novel={novel} active="world-notes" open={navOpen} onClose={()=>setNavOpen(false)} beforeNavigate={saveBeforeNavigate}/>{navOpen&&<button className="scrim" onClick={()=>setNavOpen(false)}/>}<main className="section-main character-page world-notes-page">
    <header className="character-top"><div className="section-top-left"><button className="menu-button" onClick={()=>setNavOpen(true)}>☰</button></div><div><small>{novel.title}</small><strong>World Notes</strong></div><div className="character-top-actions"><span className={save==="error"?"save-error":""} onClick={()=>save==="error"&&active&&persist(active)}>{save==="saving"?"Saving…":save==="error"?"Save failed · Retry":"Saved"}</span><button className="primary" onClick={addWorldNote}>＋ World note</button></div></header>
    <section className="character-layout">
      <aside className="character-index world-note-index"><div className="character-index-title"><div><small>STORY BIBLE</small><strong>World Notes</strong></div><b>{notes.length}</b></div><input className="character-search" value={queryText} onChange={e=>setQueryText(e.target.value)} placeholder="Search world notes…"/><select className="world-note-filter" value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="">All categories</option>{categoryChoices.map(category=><option key={category} value={category}>{category}</option>)}</select><div className="character-list world-note-list">{filtered.map(note=>{const image=ordered(note.images)[0];return <button key={note.id} className={note.id===active?.id?"active":""} onClick={()=>select(note.id)}>{image?<img className="location-list-photo" src={image.url} alt=""/>:<span className="world-note-marker">◇</span>}<div><strong>{note.name||"Unnamed World Note"}</strong><small>{note.category||"Lore"}</small></div></button>})}{notes.length>0&&!filtered.length&&<p>No world notes match those filters.</p>}</div></aside>
      <main className="character-editor world-note-editor">{active?<><div className="character-hero world-note-hero"><button className="location-cover-drop world-note-cover" onClick={()=>setAssetPickerOpen(true)}>{primaryImage?<img src={primaryImage.url} alt={active.name}/>:<span>◇</span>}<i>{primaryImage?"Change / add":"Add image"}</i></button><div><small>WORLD NOTE</small><input className="character-name world-note-name" value={active.name} onChange={e=>update({name:e.target.value})} placeholder="Name"/><p className="location-subtitle">{active.category||"Lore"}</p></div><button className="character-delete" onClick={()=>{setDeletePhrase("");setDeleting(true)}}>Delete</button></div>
        {imageError&&<p className="character-upload-error">{imageError}</p>}
        <section className="character-section"><h2>Identity</h2><div className="world-note-meta"><label><span>Aliases / alternate names</span><input value={active.aliases} onChange={e=>update({aliases:e.target.value})} placeholder="Other names used in the manuscript…"/></label><label><span>Category</span><input list="world-note-categories" value={active.category} onChange={e=>update({category:e.target.value})} placeholder="Faction, religion, artifact…"/><datalist id="world-note-categories">{categories.map(category=><option key={category} value={category}/>)}</datalist></label></div></section>
        <section className="character-section character-images-section"><div className="character-section-title"><div><h2>Visual reference</h2><p>Keep symbols, diagrams, artifacts, creatures and other reference images with this entry.</p></div><button onClick={()=>setAssetPickerOpen(true)}>＋ Add image</button></div>{activeImages.length?<div className="character-gallery">{activeImages.map((image,index)=><article key={image.id} className={index===0?"primary-image":""}><div className="character-gallery-image"><img src={image.url} alt={image.caption||active.name}/>{index===0&&<b>Primary</b>}</div><input defaultValue={image.caption} onBlur={e=>saveCaption(image,e.target.value)} placeholder="Caption or reference note"/><footer>{index!==0&&<button onClick={()=>makePrimary(image)}>Use as primary</button>}<button className="danger" onClick={()=>removeImage(image)}>Remove</button></footer></article>)}</div>:<button className="character-image-empty" onClick={()=>setAssetPickerOpen(true)}><strong>Add visual reference</strong><span>Choose an existing project image or upload a new one.</span></button>}</section>
        <section className="character-section"><h2>Lore</h2><div className="character-grid"><Field label="Summary" value={active.summary} onChange={value=>update({summary:value})} placeholder="What is this, at a glance?"/><Field label="Story significance" value={active.significance} onChange={value=>update({significance:value})} placeholder="Why does it matter to the story?"/><Field label="Lore & details" value={active.details} onChange={value=>update({details:value})} placeholder="Origins, rules, beliefs, mechanics, history, customs, properties…" large/></div></section>
        <section className="character-section world-connections"><div className="character-section-title"><div><h2>Connections</h2><p>Connect this lore entry to the rest of the Story Bible.</p></div></div>
          <div className="world-connection-group"><div className="world-connection-heading"><div><strong>Characters</strong><span>People tied to this entry.</span></div><button disabled={!availableCharacters.length} onClick={()=>beginLink("character")}>＋ Character</button></div>{activeCharacterLinks.length?<div className="world-link-grid">{activeCharacterLinks.map(link=>{const item=characters.find(character=>character.id===link.characterId);if(!item)return null;return <article key={link.id}><div className="world-link-person">{item.portraitUrl?<img src={item.portraitUrl} alt=""/>:<span>{initials(item.name)}</span>}<div><strong>{item.name}</strong><small>{item.role||"Character"}</small></div></div><input value={link.label} onChange={e=>saveCharacterLink(link,{label:e.target.value})} placeholder="Relationship"/><textarea defaultValue={link.notes} onBlur={e=>saveCharacterLink(link,{notes:e.target.value})} placeholder="Connection notes…"/><button onClick={()=>removeLink("character",link.id)}>Remove</button></article>})}</div>:<p className="world-link-empty">No characters linked.</p>}</div>
          <div className="world-connection-group"><div className="world-connection-heading"><div><strong>Locations</strong><span>Places where this lore exists or matters.</span></div><button disabled={!availableLocations.length} onClick={()=>beginLink("location")}>＋ Location</button></div>{activeLocationLinks.length?<div className="world-link-grid">{activeLocationLinks.map(link=>{const item=locations.find(location=>location.id===link.locationId);if(!item)return null;return <article key={link.id}><div className="world-link-person">{item.imageUrl?<img className="world-link-square" src={item.imageUrl} alt=""/>:<span className="world-link-square">⌖</span>}<div><strong>{item.name}</strong><small>{[item.type,item.region].filter(Boolean).join(" · ")||"Location"}</small></div></div><input value={link.label} onChange={e=>saveLocationLink(link,{label:e.target.value})} placeholder="Relationship"/><textarea defaultValue={link.notes} onBlur={e=>saveLocationLink(link,{notes:e.target.value})} placeholder="Connection notes…"/><button onClick={()=>removeLink("location",link.id)}>Remove</button></article>})}</div>:<p className="world-link-empty">No locations linked.</p>}</div>
          <div className="world-connection-group"><div className="world-connection-heading"><div><strong>Other world notes</strong><span>Build relationships between factions, artifacts, events and lore.</span></div><button disabled={!availableNotes.length} onClick={()=>beginLink("note")}>＋ World note</button></div>{activeRelations.length?<div className="world-link-grid">{activeRelations.map(link=>{const otherId=link.sourceId===active.id?link.targetId:link.sourceId,item=notes.find(note=>note.id===otherId);if(!item)return null;return <article key={link.id}><button className="world-related-note" onClick={()=>select(item.id)}><span>◇</span><div><strong>{item.name}</strong><small>{item.category}</small></div></button><input value={link.label} onChange={e=>saveRelation(link,{label:e.target.value})} placeholder="Relationship"/><textarea defaultValue={link.notes} onBlur={e=>saveRelation(link,{notes:e.target.value})} placeholder="Connection notes…"/><button onClick={()=>removeLink("note",link.id)}>Remove</button></article>})}</div>:<p className="world-link-empty">No other world notes linked.</p>}</div>
        </section>
        <section className="character-section"><h2>Private notes</h2><div className="character-grid"><Field label="Notes" value={active.notes} onChange={value=>update({notes:value})} placeholder="Continuity details, research, spoilers and anything else to remember…" large/></div></section>
      </>:<div className="character-empty world-note-empty"><div className="world-note-empty-marker">◇</div><h1>Build your lore</h1><p>Create factions, cultures, religions, magic systems, artifacts, events—or any category your story needs.</p><button className="primary" onClick={addWorldNote}>＋ Create world note</button></div>}</main>
    </section>
    {assetPickerOpen&&active&&<AssetPicker novelId={novel.id} title={`Add image to ${active.name||"world note"}`} onClose={()=>setAssetPickerOpen(false)} onSelect={attachAsset}/>}
    {addKind&&active&&<div className="modal-backdrop" onMouseDown={()=>setAddKind(null)}><section className="world-link-dialog" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><small>CONNECT STORY BIBLE</small><h2>Link {addKind==="character"?"character":addKind==="location"?"location":"world note"}</h2><label><span>{addKind==="character"?"Character":addKind==="location"?"Location":"World note"}</span><select value={linkTarget} onChange={e=>setLinkTarget(e.target.value)}>{(addKind==="character"?availableCharacters:addKind==="location"?availableLocations:availableNotes).map((item:any)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>Relationship label</span><input value={linkLabel} onChange={e=>setLinkLabel(e.target.value)} placeholder="Founded by, worshipped in, powered by…"/></label><label><span>Notes <i>optional</i></span><textarea value={linkNotes} onChange={e=>setLinkNotes(e.target.value)} placeholder="What matters about this connection?"/></label>{linkError&&<p>{linkError}</p>}<footer><button onClick={()=>setAddKind(null)}>Cancel</button><button className="primary" disabled={!linkTarget} onClick={addLink}>Add connection</button></footer></section></div>}
    {deleting&&active&&<div className="modal-backdrop delete-backdrop" onMouseDown={()=>setDeleting(false)}><form className="delete-dialog" onSubmit={e=>{e.preventDefault();deleteWorldNote()}} onMouseDown={e=>e.stopPropagation()}><small>PERMANENT DELETION</small><h2>Delete world note?</h2><div className="delete-name">{active.name}</div><p>This removes the entry, its image links and all Story Bible connections. <strong>This cannot be undone.</strong></p><label>Type <b>DELETE</b> to confirm<input autoFocus value={deletePhrase} onChange={e=>setDeletePhrase(e.target.value)} autoComplete="off"/></label><footer><button type="button" onClick={()=>setDeleting(false)}>Cancel</button><button className="delete-confirm" disabled={deletePhrase!=="DELETE"}>Delete permanently</button></footer></form></div>}
  </main></div>;
}
