"use client";
import {DragEvent,useEffect,useMemo,useRef,useState} from "react";
import WorkspaceSectionSidebar from "../../WorkspaceSectionSidebar";
import RelationshipMap,{type Relationship} from "./RelationshipMap";

type CharacterImage={id:string;assetId:string;caption:string;position:number;url:string};
type Character={id:string;name:string;aliases:string;role:string;pronouns:string;age:string;description:string;appearance:string;personality:string;background:string;goals:string;conflict:string;arc:string;notes:string;position:number;images:CharacterImage[]};
type SaveState="saved"|"saving"|"error";
const editable=(c:Character)=>({name:c.name,aliases:c.aliases,role:c.role,pronouns:c.pronouns,age:c.age,description:c.description,appearance:c.appearance,personality:c.personality,background:c.background,goals:c.goals,conflict:c.conflict,arc:c.arc,notes:c.notes});
const snap=(c:Character)=>JSON.stringify(editable(c));
const relationshipOptions=[["PARENT","Parent of"],["CHILD","Child of"],["SIBLING","Sibling"],["PARTNER","Partner"],["FRIEND","Friend"],["ALLY","Ally"],["RIVAL","Rival"],["ENEMY","Enemy"],["MENTOR","Mentor of"],["STUDENT","Student of"],["OTHER","Other"]] as const;

function initials(name:string){return name.trim().split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()).join("")||"?"}
function ordered(images:CharacterImage[]){return [...images].sort((a,b)=>a.position-b.position)}
function otherId(r:Relationship,id:string){return r.sourceId===id?r.targetId:r.sourceId}
function relationshipLabel(r:Relationship,id:string){
  if(r.label)return r.label;
  if(r.type==="PARENT")return r.sourceId===id?"Parent of":"Child of";
  if(r.type==="MENTOR")return r.sourceId===id?"Mentor of":"Student of";
  return ({SIBLING:"Sibling",PARTNER:"Partner",FRIEND:"Friend",ALLY:"Ally",RIVAL:"Rival",ENEMY:"Enemy",OTHER:"Related"} as Record<string,string>)[r.type]||"Related";
}

export default function CharacterBible({username,novel,initialCharacters,initialRelationships}:{username:string;novel:{id:string;title:string};initialCharacters:Character[];initialRelationships:Relationship[]}){
  const [characters,setCharacters]=useState(initialCharacters),[relationships,setRelationships]=useState(initialRelationships),[activeId,setActiveId]=useState(initialCharacters[0]?.id??""),[queryText,setQueryText]=useState(""),[save,setSave]=useState<SaveState>("saved"),[deleting,setDeleting]=useState(false),[deletePhrase,setDeletePhrase]=useState(""),[navOpen,setNavOpen]=useState(false),[uploading,setUploading]=useState(false),[uploadError,setUploadError]=useState(""),[addingRelationship,setAddingRelationship]=useState(false),[relationshipTarget,setRelationshipTarget]=useState(""),[relationshipType,setRelationshipType]=useState("FRIEND"),[relationshipLabelText,setRelationshipLabelText]=useState(""),[relationshipNotes,setRelationshipNotes]=useState(""),[relationshipError,setRelationshipError]=useState(""),[mapOpen,setMapOpen]=useState(false);
  const charsRef=useRef(initialCharacters),activeRef=useRef(activeId),timers=useRef(new Map<string,ReturnType<typeof setTimeout>>()),saved=useRef(new Map(initialCharacters.map(c=>[c.id,snap(c)]))),seq=useRef(new Map<string,number>()),files=useRef<HTMLInputElement>(null);
  const active=characters.find(c=>c.id===activeId)??characters[0],activeImages=ordered(active?.images??[]),portrait=activeImages[0],activeRelationships=active?relationships.filter(r=>r.sourceId===active.id||r.targetId===active.id):[];
  useEffect(()=>{charsRef.current=characters},[characters]);useEffect(()=>{activeRef.current=activeId},[activeId]);

  async function persist(c:Character,keepalive=false){const body=snap(c);if(saved.current.get(c.id)===body)return true;const n=(seq.current.get(c.id)??0)+1;seq.current.set(c.id,n);setSave("saving");try{const r=await fetch(`/api/characters/${c.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(editable(c)),keepalive});if(!r.ok)throw new Error();if(seq.current.get(c.id)===n){saved.current.set(c.id,body);setSave("saved")}return true}catch{if(seq.current.get(c.id)===n)setSave("error");return false}}
  function schedule(c:Character){const old=timers.current.get(c.id);if(old)clearTimeout(old);setSave("saving");timers.current.set(c.id,setTimeout(()=>{timers.current.delete(c.id);persist(c)},650))}
  function update(patch:Partial<Character>){setCharacters(list=>list.map(c=>{if(c.id!==activeRef.current)return c;const next={...c,...patch};schedule(next);return next}))}
  function updateImages(characterId:string,fn:(images:CharacterImage[])=>CharacterImage[]){setCharacters(list=>list.map(c=>c.id===characterId?{...c,images:fn(c.images)}:c))}
  async function select(id:string){const current=charsRef.current.find(c=>c.id===activeRef.current);if(current&&current.id!==id){const timer=timers.current.get(current.id);if(timer){clearTimeout(timer);timers.current.delete(current.id)}await persist(current)}setActiveId(id);setUploadError("");setAddingRelationship(false);setRelationshipError("")}
  async function addCharacter(){const current=charsRef.current.find(c=>c.id===activeRef.current);if(current)await persist(current);const r=await fetch("/api/characters",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({novelId:novel.id})});if(!r.ok)return;const raw=await r.json();const c={...raw,images:[]} as Character;saved.current.set(c.id,snap(c));setCharacters(v=>[...v,c]);setActiveId(c.id);setQueryText("");setTimeout(()=>document.querySelector<HTMLInputElement>(".character-name")?.select(),30)}
  async function deleteCharacter(){if(!active||deletePhrase!=="DELETE")return;const timer=timers.current.get(active.id);if(timer){clearTimeout(timer);timers.current.delete(active.id)}const doomedId=active.id,r=await fetch(`/api/characters/${doomedId}`,{method:"DELETE"});if(!r.ok)return;const index=characters.findIndex(c=>c.id===doomedId),next=characters.filter(c=>c.id!==doomedId);saved.current.delete(doomedId);seq.current.delete(doomedId);setCharacters(next);charsRef.current=next;setRelationships(v=>v.filter(rel=>rel.sourceId!==doomedId&&rel.targetId!==doomedId));setActiveId(next[Math.max(0,index-1)]?.id??next[0]?.id??"");setDeleting(false);setDeletePhrase("")}
  async function saveBeforeNavigate(){const current=charsRef.current.find(c=>c.id===activeRef.current);if(current){const timer=timers.current.get(current.id);if(timer){clearTimeout(timer);timers.current.delete(current.id)}await persist(current)}}
  useEffect(()=>{const flush=()=>{for(const t of timers.current.values())clearTimeout(t);timers.current.clear();for(const c of charsRef.current)if(saved.current.get(c.id)!==snap(c))persist(c,true)};const visibility=()=>{if(document.visibilityState==="hidden")flush()};window.addEventListener("pagehide",flush);document.addEventListener("visibilitychange",visibility);return()=>{window.removeEventListener("pagehide",flush);document.removeEventListener("visibilitychange",visibility)}},[]);

  async function upload(selected:File[]){if(!active||!selected.length)return;setUploading(true);setUploadError("");for(const file of selected){const data=new FormData();data.set("novelId",novel.id);data.set("file",file);const assetResponse=await fetch("/api/assets",{method:"POST",body:data});if(!assetResponse.ok){const error=await assetResponse.json().catch(()=>({error:"Image upload failed."}));setUploadError(error.error||"Image upload failed.");continue}const asset=await assetResponse.json();const linkResponse=await fetch(`/api/characters/${active.id}/images`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({assetId:asset.id})});if(!linkResponse.ok){setUploadError("The image uploaded but could not be attached to this character.");continue}const image=await linkResponse.json() as CharacterImage;updateImages(active.id,images=>[...images,image])}setUploading(false);if(files.current)files.current.value=""}
  function dropped(event:DragEvent<HTMLElement>){event.preventDefault();const incoming=Array.from(event.dataTransfer.files).filter(file=>file.type.startsWith("image/"));upload(incoming)}
  async function saveCaption(image:CharacterImage,caption:string){if(!active)return;updateImages(active.id,images=>images.map(item=>item.id===image.id?{...item,caption}:item));await fetch(`/api/characters/${active.id}/images/${image.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({caption})})}
  async function makePortrait(image:CharacterImage){if(!active)return;const r=await fetch(`/api/characters/${active.id}/images/${image.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({caption:image.caption,makePrimary:true})});if(!r.ok)return;updateImages(active.id,images=>{const rest=images.filter(item=>item.id!==image.id).sort((a,b)=>a.position-b.position).map((item,index)=>({...item,position:index+1}));return [{...image,position:0},...rest]})}
  async function removeImage(image:CharacterImage){if(!active||!confirm("Remove this image from the character bio? The uploaded project asset itself will be kept."))return;const r=await fetch(`/api/characters/${active.id}/images/${image.id}`,{method:"DELETE"});if(r.ok)updateImages(active.id,images=>images.filter(item=>item.id!==image.id).map((item,index)=>({...item,position:index})))}

  function startRelationship(){if(!active)return;const first=characters.find(c=>c.id!==active.id);setRelationshipTarget(first?.id??"");setRelationshipType("FRIEND");setRelationshipLabelText("");setRelationshipNotes("");setRelationshipError("");setAddingRelationship(true)}
  async function addRelationship(){if(!active||!relationshipTarget)return;setRelationshipError("");const r=await fetch("/api/character-relationships",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({novelId:novel.id,sourceId:active.id,targetId:relationshipTarget,type:relationshipType,label:relationshipLabelText,notes:relationshipNotes})});if(!r.ok){const data=await r.json().catch(()=>({error:"Relationship could not be added."}));setRelationshipError(data.error||"Relationship could not be added.");return}const relation=await r.json() as Relationship;setRelationships(v=>[...v,relation]);setAddingRelationship(false)}
  async function saveRelationship(relation:Relationship,patch:Partial<Pick<Relationship,"label"|"notes">>){const next={...relation,...patch};setRelationships(v=>v.map(r=>r.id===relation.id?next:r));await fetch(`/api/character-relationships/${relation.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({label:next.label,notes:next.notes})})}
  async function removeRelationship(relation:Relationship){if(!confirm("Remove this relationship? The character profiles will be kept."))return;const r=await fetch(`/api/character-relationships/${relation.id}`,{method:"DELETE"});if(r.ok)setRelationships(v=>v.filter(x=>x.id!==relation.id))}

  const filtered=useMemo(()=>{const q=queryText.trim().toLowerCase();if(!q)return characters;return characters.filter(c=>[c.name,c.aliases,c.role].some(v=>v.toLowerCase().includes(q)))},[characters,queryText]);
  const Field=({label,value,onChange,placeholder,large=false}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string;large?:boolean})=><label className={large?"character-field character-field-large":"character-field"}><span>{label}</span><textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>;

  return <div className="app section-shell"><WorkspaceSectionSidebar username={username} novel={novel} active="characters" open={navOpen} onClose={()=>setNavOpen(false)} beforeNavigate={saveBeforeNavigate}/>{navOpen&&<button className="scrim" onClick={()=>setNavOpen(false)}/>}<main className="section-main character-page">
    <header className="character-top"><div className="section-top-left"><button className="menu-button" onClick={()=>setNavOpen(true)}>☰</button></div><div><small>{novel.title}</small><strong>Characters</strong></div><div className="character-top-actions"><span className={save==="error"?"save-error":""} onClick={()=>save==="error"&&active&&persist(active)}>{save==="saving"?"Saving…":save==="error"?"Save failed · Retry":"Saved"}</span>{characters.length>0&&<button onClick={()=>setMapOpen(true)}>Relationships</button>}<button className="primary" onClick={addCharacter}>＋ Character</button></div></header>
    <section className="character-layout">
      <aside className="character-index"><div className="character-index-title"><div><small>STORY BIBLE</small><strong>Cast</strong></div><b>{characters.length}</b></div><input className="character-search" value={queryText} onChange={e=>setQueryText(e.target.value)} placeholder="Search characters…"/><div className="character-list">{filtered.map(c=>{const image=ordered(c.images)[0];return <button key={c.id} className={c.id===active?.id?"active":""} onClick={()=>select(c.id)}>{image?<img className="character-list-photo" src={image.url} alt=""/>:<span>{initials(c.name)}</span>}<div><strong>{c.name||"Unnamed Character"}</strong><small>{c.role||c.aliases||"No role yet"}</small></div></button>})}{characters.length>0&&!filtered.length&&<p>No characters match that search.</p>}</div></aside>
      <main className="character-editor">{active?<><div className="character-hero"><div className="character-portrait-drop" onDragOver={e=>e.preventDefault()} onDrop={dropped} onClick={()=>files.current?.click()}>{portrait?<img src={portrait.url} alt={active.name}/>:<div className="character-avatar">{initials(active.name)}</div>}<span>{uploading?"Uploading…":portrait?"Change / add":"Add image"}</span></div><input ref={files} hidden multiple type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>upload(Array.from(e.target.files??[]))}/><div><small>CHARACTER PROFILE</small><input className="character-name" value={active.name} onChange={e=>update({name:e.target.value})} placeholder="Character name"/><input className="character-role" value={active.role} onChange={e=>update({role:e.target.value})} placeholder="Role in the story — protagonist, mentor, rival…"/></div><button className="character-delete" onClick={()=>{setDeletePhrase("");setDeleting(true)}}>Delete</button></div>
        {uploadError&&<p className="character-upload-error">{uploadError}</p>}
        <section className="character-section character-images-section"><div className="character-section-title"><div><h2>Visual reference</h2><p>Keep portraits, costume ideas, sketches and other reference images with this character.</p></div><button onClick={()=>files.current?.click()} disabled={uploading}>{uploading?"Uploading…":"＋ Add images"}</button></div>{activeImages.length?<div className="character-gallery">{activeImages.map((image,index)=><article key={image.id} className={index===0?"primary-image":""}><div className="character-gallery-image"><img src={image.url} alt={image.caption||active.name}/>{index===0&&<b>Portrait</b>}</div><input defaultValue={image.caption} onBlur={e=>saveCaption(image,e.target.value)} placeholder="Caption or reference note"/><footer>{index!==0&&<button onClick={()=>makePortrait(image)}>Use as portrait</button>}<button className="danger" onClick={()=>removeImage(image)}>Remove</button></footer></article>)}</div>:<button className="character-image-empty" onClick={()=>files.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={dropped}><strong>Drop images here</strong><span>or click to choose JPG, PNG, WebP or GIF files up to 10 MB each.</span></button>}</section>
        <section className="character-section"><h2>Identity</h2><div className="character-identity"><label><span>Aliases / nicknames</span><input value={active.aliases} onChange={e=>update({aliases:e.target.value})} placeholder="Names other characters use"/></label><label><span>Pronouns</span><input value={active.pronouns} onChange={e=>update({pronouns:e.target.value})} placeholder="e.g. she / her"/></label><label><span>Age</span><input value={active.age} onChange={e=>update({age:e.target.value})} placeholder="Exact or approximate"/></label></div></section>
        <section className="character-section relationship-section"><div className="character-section-title"><div><h2>Relationships</h2><p>Connect this character to the rest of your cast.</p></div><div><button onClick={()=>setMapOpen(true)}>View map</button><button onClick={startRelationship} disabled={characters.length<2}>＋ Relationship</button></div></div>
          {addingRelationship&&<div className="relationship-form"><label><span>Character</span><select value={relationshipTarget} onChange={e=>setRelationshipTarget(e.target.value)}>{characters.filter(c=>c.id!==active.id).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><span>Relationship</span><select value={relationshipType} onChange={e=>setRelationshipType(e.target.value)}>{relationshipOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><span>Custom label <i>optional</i></span><input value={relationshipLabelText} onChange={e=>setRelationshipLabelText(e.target.value)} placeholder="e.g. Twin, ex-partner, sworn brother"/></label><label className="relationship-notes-field"><span>Notes <i>optional</i></span><textarea value={relationshipNotes} onChange={e=>setRelationshipNotes(e.target.value)} placeholder="How do they know each other? What matters about the relationship?"/></label>{relationshipError&&<p>{relationshipError}</p>}<footer><button onClick={()=>setAddingRelationship(false)}>Cancel</button><button className="primary" disabled={!relationshipTarget} onClick={addRelationship}>Add relationship</button></footer></div>}
          {activeRelationships.length?<div className="relationship-list">{activeRelationships.map(relation=>{const other=characters.find(c=>c.id===otherId(relation,active.id));if(!other)return null;const photo=ordered(other.images)[0];return <article key={relation.id}><button className="relationship-person" onClick={()=>select(other.id)}>{photo?<img src={photo.url} alt=""/>:<span>{initials(other.name)}</span>}<div><b>{relationshipLabel(relation,active.id)}</b><strong>{other.name}</strong><small>{other.role||"Open character bio"}</small></div></button><input defaultValue={relation.label} onBlur={e=>saveRelationship(relation,{label:e.target.value})} placeholder="Custom relationship label"/><textarea defaultValue={relation.notes} onBlur={e=>saveRelationship(relation,{notes:e.target.value})} placeholder="Relationship notes…"/><button className="relationship-remove" onClick={()=>removeRelationship(relation)}>Remove</button></article>})}</div>:!addingRelationship&&<div className="relationship-empty"><strong>No relationships yet</strong><span>{characters.length<2?"Create another character first, then you can link them here.":"Add a relationship to start building the cast around this character."}</span></div>}
        </section>
        <section className="character-section"><h2>On the page</h2><div className="character-grid"><Field label="Description" value={active.description} onChange={v=>update({description:v})} placeholder="Who are they at a glance?"/><Field label="Appearance" value={active.appearance} onChange={v=>update({appearance:v})} placeholder="Physical appearance, clothing, mannerisms…"/><Field label="Personality" value={active.personality} onChange={v=>update({personality:v})} placeholder="Temperament, habits, virtues, flaws…"/><Field label="Goals & motivations" value={active.goals} onChange={v=>update({goals:v})} placeholder="What do they want, and why?"/></div></section>
        <section className="character-section"><h2>Under the surface</h2><div className="character-grid"><Field label="Background" value={active.background} onChange={v=>update({background:v})} placeholder="History, upbringing, formative events…" large/><Field label="Conflict" value={active.conflict} onChange={v=>update({conflict:v})} placeholder="Internal and external pressures…"/><Field label="Character arc" value={active.arc} onChange={v=>update({arc:v})} placeholder="Where do they begin, what changes, and where do they end?"/><Field label="Private notes" value={active.notes} onChange={v=>update({notes:v})} placeholder="Anything else you need to remember…" large/></div></section>
      </>:<div className="character-empty"><div className="character-avatar">?</div><h1>Build your cast</h1><p>Create your first character and keep the details that matter beside your manuscript.</p><button className="primary" onClick={addCharacter}>＋ Create character</button></div>}</main>
    </section>
    {mapOpen&&active&&<RelationshipMap characters={characters} relationships={relationships} initialFocusId={active.id} onClose={()=>setMapOpen(false)} onOpenProfile={select}/>}
    {deleting&&active&&<div className="modal-backdrop delete-backdrop" onMouseDown={()=>setDeleting(false)}><form className="delete-dialog" onSubmit={e=>{e.preventDefault();deleteCharacter()}} onMouseDown={e=>e.stopPropagation()}><small>PERMANENT DELETION</small><h2>Delete character?</h2><div className="delete-name">{active.name}</div><p>This removes the character profile, its image links and any relationships involving this character. <strong>This cannot be undone.</strong></p><label>Type <b>DELETE</b> to confirm<input autoFocus value={deletePhrase} onChange={e=>setDeletePhrase(e.target.value)} autoComplete="off"/></label><footer><button type="button" onClick={()=>setDeleting(false)}>Cancel</button><button className="delete-confirm" disabled={deletePhrase!=="DELETE"}>Delete permanently</button></footer></form></div>}
  </main></div>;
}
