"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import WorkspaceSectionSidebar from "../../../WorkspaceSectionSidebar";

type Character={id:string;name:string;aliases:string;role:string;pronouns:string;age:string;description:string;appearance:string;personality:string;background:string;goals:string;conflict:string;arc:string;notes:string;position:number};
type SaveState="saved"|"saving"|"error";
const editable=(c:Character)=>({name:c.name,aliases:c.aliases,role:c.role,pronouns:c.pronouns,age:c.age,description:c.description,appearance:c.appearance,personality:c.personality,background:c.background,goals:c.goals,conflict:c.conflict,arc:c.arc,notes:c.notes});
const snap=(c:Character)=>JSON.stringify(editable(c));

function initials(name:string){return name.trim().split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()).join("")||"?"}

export default function CharacterBible({username,novel,initialCharacters}:{username:string;novel:{id:string;title:string};initialCharacters:Character[]}){
  const [characters,setCharacters]=useState(initialCharacters),[activeId,setActiveId]=useState(initialCharacters[0]?.id??""),[queryText,setQueryText]=useState(""),[save,setSave]=useState<SaveState>("saved"),[deleting,setDeleting]=useState(false),[deletePhrase,setDeletePhrase]=useState(""),[navOpen,setNavOpen]=useState(false);
  const charsRef=useRef(initialCharacters),activeRef=useRef(activeId),timers=useRef(new Map<string,ReturnType<typeof setTimeout>>()),saved=useRef(new Map(initialCharacters.map(c=>[c.id,snap(c)]))),seq=useRef(new Map<string,number>());
  const active=characters.find(c=>c.id===activeId)??characters[0];
  useEffect(()=>{charsRef.current=characters},[characters]);useEffect(()=>{activeRef.current=activeId},[activeId]);

  async function persist(c:Character,keepalive=false){
    const body=snap(c);if(saved.current.get(c.id)===body)return true;
    const n=(seq.current.get(c.id)??0)+1;seq.current.set(c.id,n);setSave("saving");
    try{
      const r=await fetch(`/api/characters/${c.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(editable(c)),keepalive});
      if(!r.ok)throw new Error();
      if(seq.current.get(c.id)===n){saved.current.set(c.id,body);setSave("saved")}
      return true;
    }catch{if(seq.current.get(c.id)===n)setSave("error");return false}
  }
  function schedule(c:Character){const old=timers.current.get(c.id);if(old)clearTimeout(old);setSave("saving");timers.current.set(c.id,setTimeout(()=>{timers.current.delete(c.id);persist(c)},650))}
  function update(patch:Partial<Character>){setCharacters(list=>list.map(c=>{if(c.id!==activeRef.current)return c;const next={...c,...patch};schedule(next);return next}))}
  async function select(id:string){const current=charsRef.current.find(c=>c.id===activeRef.current);if(current&&current.id!==id){const timer=timers.current.get(current.id);if(timer){clearTimeout(timer);timers.current.delete(current.id)}await persist(current)}setActiveId(id)}
  async function addCharacter(){const current=charsRef.current.find(c=>c.id===activeRef.current);if(current)await persist(current);const r=await fetch("/api/characters",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({novelId:novel.id})});if(!r.ok)return;const c=await r.json() as Character;saved.current.set(c.id,snap(c));setCharacters(v=>[...v,c]);setActiveId(c.id);setQueryText("");setTimeout(()=>document.querySelector<HTMLInputElement>(".character-name")?.select(),30)}
  async function deleteCharacter(){if(!active||deletePhrase!=="DELETE")return;const timer=timers.current.get(active.id);if(timer){clearTimeout(timer);timers.current.delete(active.id)}const r=await fetch(`/api/characters/${active.id}`,{method:"DELETE"});if(!r.ok)return;const index=characters.findIndex(c=>c.id===active.id),next=characters.filter(c=>c.id!==active.id);saved.current.delete(active.id);seq.current.delete(active.id);setCharacters(next);charsRef.current=next;setActiveId(next[Math.max(0,index-1)]?.id??next[0]?.id??"");setDeleting(false);setDeletePhrase("")}
  async function saveBeforeNavigate(){const current=charsRef.current.find(c=>c.id===activeRef.current);if(current){const timer=timers.current.get(current.id);if(timer){clearTimeout(timer);timers.current.delete(current.id)}await persist(current)}}
  useEffect(()=>{const flush=()=>{for(const t of timers.current.values())clearTimeout(t);timers.current.clear();for(const c of charsRef.current)if(saved.current.get(c.id)!==snap(c))persist(c,true)};const visibility=()=>{if(document.visibilityState==="hidden")flush()};window.addEventListener("pagehide",flush);document.addEventListener("visibilitychange",visibility);return()=>{window.removeEventListener("pagehide",flush);document.removeEventListener("visibilitychange",visibility)}},[]);
  const filtered=useMemo(()=>{const q=queryText.trim().toLowerCase();if(!q)return characters;return characters.filter(c=>[c.name,c.aliases,c.role].some(v=>v.toLowerCase().includes(q)))},[characters,queryText]);
  const Field=({label,value,onChange,placeholder,large=false}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string;large?:boolean})=><label className={large?"character-field character-field-large":"character-field"}><span>{label}</span><textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>;

  return <div className="app section-shell"><WorkspaceSectionSidebar username={username} novel={novel} active="characters" open={navOpen} onClose={()=>setNavOpen(false)} beforeNavigate={saveBeforeNavigate}/>{navOpen&&<button className="scrim" onClick={()=>setNavOpen(false)}/>}<main className="section-main character-page">
    <header className="character-top"><div className="section-top-left"><button className="menu-button" onClick={()=>setNavOpen(true)}>☰</button></div><div><small>{novel.title}</small><strong>Characters</strong></div><div className="character-top-actions"><span className={save==="error"?"save-error":""} onClick={()=>save==="error"&&active&&persist(active)}>{save==="saving"?"Saving…":save==="error"?"Save failed · Retry":"Saved"}</span><button className="primary" onClick={addCharacter}>＋ Character</button></div></header>
    <section className="character-layout">
      <aside className="character-index"><div className="character-index-title"><div><small>STORY BIBLE</small><strong>Cast</strong></div><b>{characters.length}</b></div><input className="character-search" value={queryText} onChange={e=>setQueryText(e.target.value)} placeholder="Search characters…"/><div className="character-list">{filtered.map(c=><button key={c.id} className={c.id===active?.id?"active":""} onClick={()=>select(c.id)}><span>{initials(c.name)}</span><div><strong>{c.name||"Unnamed Character"}</strong><small>{c.role||c.aliases||"No role yet"}</small></div></button>)}{characters.length>0&&!filtered.length&&<p>No characters match that search.</p>}</div></aside>
      <main className="character-editor">{active?<><div className="character-hero"><div className="character-avatar">{initials(active.name)}</div><div><small>CHARACTER PROFILE</small><input className="character-name" value={active.name} onChange={e=>update({name:e.target.value})} placeholder="Character name"/><input className="character-role" value={active.role} onChange={e=>update({role:e.target.value})} placeholder="Role in the story — protagonist, mentor, rival…"/></div><button className="character-delete" onClick={()=>{setDeletePhrase("");setDeleting(true)}}>Delete</button></div>
        <section className="character-section"><h2>Identity</h2><div className="character-identity"><label><span>Aliases / nicknames</span><input value={active.aliases} onChange={e=>update({aliases:e.target.value})} placeholder="Names other characters use"/></label><label><span>Pronouns</span><input value={active.pronouns} onChange={e=>update({pronouns:e.target.value})} placeholder="e.g. she / her"/></label><label><span>Age</span><input value={active.age} onChange={e=>update({age:e.target.value})} placeholder="Exact or approximate"/></label></div></section>
        <section className="character-section"><h2>On the page</h2><div className="character-grid"><Field label="Description" value={active.description} onChange={v=>update({description:v})} placeholder="Who are they at a glance?"/><Field label="Appearance" value={active.appearance} onChange={v=>update({appearance:v})} placeholder="Physical appearance, clothing, mannerisms…"/><Field label="Personality" value={active.personality} onChange={v=>update({personality:v})} placeholder="Temperament, habits, virtues, flaws…"/><Field label="Goals & motivations" value={active.goals} onChange={v=>update({goals:v})} placeholder="What do they want, and why?"/></div></section>
        <section className="character-section"><h2>Under the surface</h2><div className="character-grid"><Field label="Background" value={active.background} onChange={v=>update({background:v})} placeholder="History, upbringing, formative events…" large/><Field label="Conflict" value={active.conflict} onChange={v=>update({conflict:v})} placeholder="Internal and external pressures…"/><Field label="Character arc" value={active.arc} onChange={v=>update({arc:v})} placeholder="Where do they begin, what changes, and where do they end?"/><Field label="Private notes" value={active.notes} onChange={v=>update({notes:v})} placeholder="Anything else you need to remember…" large/></div></section>
      </>:<div className="character-empty"><div className="character-avatar">?</div><h1>Build your cast</h1><p>Create your first character and keep the details that matter beside your manuscript.</p><button className="primary" onClick={addCharacter}>＋ Create character</button></div>}</main>
    </section>
    {deleting&&active&&<div className="modal-backdrop delete-backdrop" onMouseDown={()=>setDeleting(false)}><form className="delete-dialog" onSubmit={e=>{e.preventDefault();deleteCharacter()}} onMouseDown={e=>e.stopPropagation()}><small>PERMANENT DELETION</small><h2>Delete character?</h2><div className="delete-name">{active.name}</div><p>This removes the character profile and all of the notes stored inside it. <strong>This cannot be undone.</strong></p><label>Type <b>DELETE</b> to confirm<input autoFocus value={deletePhrase} onChange={e=>setDeletePhrase(e.target.value)} autoComplete="off"/></label><footer><button type="button" onClick={()=>setDeleting(false)}>Cancel</button><button className="delete-confirm" disabled={deletePhrase!=="DELETE"}>Delete permanently</button></footer></form></div>}
  </main></div>;
}
