"use client";
import {FormEvent,useState} from "react";
import {useRouter} from "next/navigation";
type Settings={registrationsEnabled:boolean;emailVerificationRequired:boolean;backupDownloadEnabled:boolean;backupDropboxEnabled:boolean;backupGoogleDriveEnabled:boolean;backupOneDriveEnabled:boolean};
type EmailSettings={appBaseUrl:string;smtpHost:string;smtpPort:number;smtpSecure:boolean;smtpUser:string;smtpFrom:string;passwordConfigured:boolean;source:"admin"|"environment"|"none"};
type UserRow={id:string;username:string;email:string;role:string;emailVerifiedAt:string|null;createdAt:string};
export default function AdminPanel({currentUserId,initialSettings,initialEmail,initialUsers}:{currentUserId:string;initialSettings:Settings;initialEmail:EmailSettings;initialUsers:UserRow[]}){const router=useRouter(),[settings,setSettings]=useState(initialSettings),[email,setEmail]=useState(initialEmail),[users,setUsers]=useState(initialUsers),[message,setMessage]=useState(""),[busy,setBusy]=useState("");
async function patchSettings(patch:Partial<Settings>){setBusy("settings");setMessage("");const r=await fetch("/api/admin/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(patch)}),d=await r.json();if(r.ok){setSettings(d);setMessage("Admin settings saved.")}else setMessage(d.error||"Settings could not be saved.");setBusy("")}
async function saveEmail(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy("email");setMessage("");const f=new FormData(e.currentTarget),r=await fetch("/api/admin/email-settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({appBaseUrl:f.get("appBaseUrl"),smtpHost:f.get("smtpHost"),smtpPort:Number(f.get("smtpPort")),smtpSecure:f.get("smtpSecure")==="on",smtpUser:f.get("smtpUser"),smtpPassword:f.get("smtpPassword"),smtpFrom:f.get("smtpFrom")})}),d=await r.json();if(r.ok){setEmail(d);setMessage("Email settings saved.")}else setMessage(d.error||"Email settings could not be saved.");setBusy("")}
async function testEmail(){setBusy("email-test");setMessage("");const r=await fetch("/api/admin/email-settings/test",{method:"POST"}),d=await r.json();setMessage(r.ok?d.message:(d.error||"Test email failed."));setBusy("")}
async function userAction(id:string,action:"verifyEmail"|"revokeSessions"){setBusy(`${action}:${id}`);setMessage("");const r=await fetch(`/api/admin/users/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({[action]:true})}),d=await r.json();if(r.ok){if(action==="verifyEmail")setUsers(v=>v.map(u=>u.id===id?{...u,emailVerifiedAt:d.emailVerifiedAt}:u));setMessage(action==="verifyEmail"?"Email marked as verified.":"Sessions revoked.")}else setMessage(d.error||"User action failed.");setBusy("")}
const backupToggle=(label:string,key:keyof Pick<Settings,"backupDownloadEnabled"|"backupDropboxEnabled"|"backupGoogleDriveEnabled"|"backupOneDriveEnabled">,text:string)=><label className="settings-toggle"><div><strong>{label}</strong><span>{text}</span></div><input type="checkbox" checked={settings[key]} disabled={busy==="settings"} onChange={e=>patchSettings({[key]:e.target.checked})}/></label>;
return <main className="settings-shell"><header className="settings-top"><div><button onClick={()=>router.push("/workspace")}>← Library</button><div><small>ADMINISTRATION</small><strong>Sögur Forge controls</strong></div></div><button onClick={()=>router.push("/settings")}>My settings</button></header><section className="settings-main"><div className="settings-heading"><small>ADMIN</small><h1>Server controls</h1><p>Configure access, application email and which backup options users may configure for themselves.</p></div>{message&&<button className="settings-message" onClick={()=>setMessage("")}>{message} ×</button>}<div className="settings-grid">
<section className="settings-card"><div className="settings-card-head"><div><small>ACCESS</small><h2>Registration</h2></div><span className={settings.registrationsEnabled?"status-good":"status-muted"}>{settings.registrationsEnabled?"Open":"Closed"}</span></div><label className="settings-toggle"><div><strong>Allow new registrations</strong><span>Existing users can still sign in when registration is closed.</span></div><input type="checkbox" checked={settings.registrationsEnabled} onChange={e=>patchSettings({registrationsEnabled:e.target.checked})}/></label><label className="settings-toggle"><div><strong>Require email verification</strong><span>Uses the SMTP settings configured below.</span></div><input type="checkbox" checked={settings.emailVerificationRequired} onChange={e=>patchSettings({emailVerificationRequired:e.target.checked})}/></label></section>
<section className="settings-card"><div className="settings-card-head"><div><small>BACKUP POLICY</small><h2>Allowed methods</h2></div></div><p className="settings-copy">These switches only decide what users are allowed to configure. Cloud accounts and target folders belong to each individual user.</p>{backupToggle("Download to device","backupDownloadEnabled","Allow provider-neutral ZIP backups.")}{backupToggle("Dropbox","backupDropboxEnabled","Allow users to configure their own Dropbox destination.")}{backupToggle("Google Drive","backupGoogleDriveEnabled","Allow users to configure their own Google Drive destination.")}{backupToggle("OneDrive","backupOneDriveEnabled","Allow users to configure their own OneDrive destination.")}</section>
<section className="settings-card settings-card-wide"><div className="settings-card-head"><div><small>APPLICATION EMAIL</small><h2>Email delivery</h2></div><span className={email.smtpHost?"status-good":"status-warn"}>{email.smtpHost?"Configured":"Not configured"}</span></div><p className="settings-copy">Used by Sögur Forge for verification, password resets and future account notifications. Admin settings take priority over environment-variable fallbacks.</p><form className="admin-email-form" onSubmit={saveEmail}><label><span>Public Sögur Forge URL</span><input name="appBaseUrl" defaultValue={email.appBaseUrl} placeholder="https://forge.example.com"/></label><label><span>SMTP host</span><input name="smtpHost" defaultValue={email.smtpHost} placeholder="smtp.example.com"/></label><label><span>Port</span><input name="smtpPort" type="number" min="1" max="65535" defaultValue={email.smtpPort}/></label><label className="email-secure"><span>Use TLS immediately</span><input name="smtpSecure" type="checkbox" defaultChecked={email.smtpSecure}/></label><label><span>SMTP username</span><input name="smtpUser" defaultValue={email.smtpUser} autoComplete="off"/></label><label><span>SMTP password</span><input name="smtpPassword" type="password" placeholder={email.passwordConfigured?"Saved — leave blank to keep":"Optional"} autoComplete="new-password"/></label><label><span>From address</span><input name="smtpFrom" defaultValue={email.smtpFrom} placeholder="Sögur Forge <forge@example.com>"/></label><div className="admin-email-actions"><button type="button" onClick={testEmail} disabled={busy==="email-test"}>{busy==="email-test"?"Sending…":"Send test email"}</button><button className="primary" disabled={busy==="email"}>{busy==="email"?"Saving…":"Save email settings"}</button></div></form></section>
<section className="settings-card settings-card-wide"><div className="settings-card-head"><div><small>ACCOUNTS</small><h2>Users</h2></div><span>{users.length}</span></div><div className="admin-user-list">{users.map(user=><article key={user.id}><div><strong>{user.username}{user.id===currentUserId?" · you":""}</strong><span>{user.email}</span><small>{user.role} · joined {new Date(user.createdAt).toLocaleDateString()}</small></div><div className="admin-user-status"><span className={user.emailVerifiedAt?"status-good":"status-warn"}>{user.emailVerifiedAt?"Verified":"Unverified"}</span>{!user.emailVerifiedAt&&<button onClick={()=>userAction(user.id,"verifyEmail")}>Verify</button>}<button onClick={()=>userAction(user.id,"revokeSessions")}>Revoke sessions</button></div></article>)}</div></section>
</div></section></main>}
