"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";

type Settings={registrationsEnabled:boolean;emailVerificationRequired:boolean;smtpConfigured:boolean};
type UserRow={id:string;username:string;email:string;role:string;emailVerifiedAt:string|null;createdAt:string};

export default function AdminPanel({currentUserId,initialSettings,initialUsers}:{currentUserId:string;initialSettings:Settings;initialUsers:UserRow[]}){
  const router=useRouter(),[settings,setSettings]=useState(initialSettings),[users,setUsers]=useState(initialUsers),[message,setMessage]=useState(""),[busy,setBusy]=useState("");
  async function patchSettings(patch:Partial<Settings>){setBusy("settings");setMessage("");const r=await fetch("/api/admin/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(patch)}),data=await r.json();if(r.ok){setSettings(data);setMessage("Admin settings saved.")}else setMessage(data.error||"Settings could not be saved.");setBusy("")}
  async function userAction(id:string,action:"verifyEmail"|"revokeSessions"){setBusy(`${action}:${id}`);setMessage("");const r=await fetch(`/api/admin/users/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({[action]:true})}),data=await r.json();if(r.ok){if(action==="verifyEmail")setUsers(v=>v.map(u=>u.id===id?{...u,emailVerifiedAt:data.emailVerifiedAt}:u));setMessage(action==="verifyEmail"?"Email marked as verified.":"Sessions revoked.")}else setMessage(data.error||"User action failed.");setBusy("")}
  return <main className="settings-shell"><header className="settings-top"><div><button onClick={()=>router.push("/workspace")}>← Library</button><div><small>ADMINISTRATION</small><strong>Sögur Forge controls</strong></div></div><button onClick={()=>router.push("/settings")}>My settings</button></header><section className="settings-main">
    <div className="settings-heading"><small>ADMIN</small><h1>Server controls</h1><p>Control account registration and verification without exposing server secrets to the browser.</p></div>
    {message&&<button className="settings-message" onClick={()=>setMessage("")}>{message} ×</button>}
    <div className="settings-grid">
      <section className="settings-card"><div className="settings-card-head"><div><small>ACCESS</small><h2>Registration</h2></div><span className={settings.registrationsEnabled?"status-good":"status-muted"}>{settings.registrationsEnabled?"Open":"Closed"}</span></div><label className="settings-toggle"><div><strong>Allow new registrations</strong><span>When disabled, existing accounts can still sign in.</span></div><input type="checkbox" checked={settings.registrationsEnabled} disabled={busy==="settings"} onChange={e=>patchSettings({registrationsEnabled:e.target.checked})}/></label><label className="settings-toggle"><div><strong>Require email verification</strong><span>New non-admin accounts must verify their email before signing in.</span></div><input type="checkbox" checked={settings.emailVerificationRequired} disabled={busy==="settings"} onChange={e=>patchSettings({emailVerificationRequired:e.target.checked})}/></label>{!settings.smtpConfigured&&settings.emailVerificationRequired&&<p className="settings-warning">SMTP is not configured. The first administrator can sign in, but additional registrations will be blocked until SMTP is configured or verification is disabled.</p>}<div className="settings-fact"><span>Email delivery</span><strong>{settings.smtpConfigured?"SMTP configured":"Not configured"}</strong></div></section>
      <section className="settings-card settings-card-wide"><div className="settings-card-head"><div><small>ACCOUNTS</small><h2>Users</h2></div><span>{users.length}</span></div><div className="admin-user-list">{users.map(user=><article key={user.id}><div><strong>{user.username}{user.id===currentUserId?" · you":""}</strong><span>{user.email}</span><small>{user.role} · joined {new Date(user.createdAt).toLocaleDateString()}</small></div><div className="admin-user-status"><span className={user.emailVerifiedAt?"status-good":"status-warn"}>{user.emailVerifiedAt?"Verified":"Unverified"}</span>{!user.emailVerifiedAt&&<button disabled={busy===`verifyEmail:${user.id}`} onClick={()=>userAction(user.id,"verifyEmail")}>Verify</button>}<button disabled={busy===`revokeSessions:${user.id}`} onClick={()=>userAction(user.id,"revokeSessions")}>Revoke sessions</button></div></article>)}</div></section>
    </div>
  </section></main>;
}
