"use client";
import {useMemo,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import WorkspaceSectionSidebar from "../../WorkspaceSectionSidebar";
import {CHAPTER_TEMPLATE_TAGS,renderChapterTemplateText} from "@/lib/chapter-template";

type Part={id:string;title:string;position:number};
type Chapter={id:string;partId:string|null;title:string;content:string;summary:string;status:string;position:number;templateId:string|null;headerImageAssetId:string|null};
type Template={id:string;name:string;isDefault:boolean;eyebrowPattern:string;titlePattern:string;showImage:boolean;headerImageAssetId:string|null;headerImageUrl:string|null;imageWidth:number;imageAlign:string};

function plainWords(html:string){const value=html.replace(/<[^>]*>/g," ").replace(/&nbsp;/g," ").trim();return value?value.split(/\s+/).length:0}
function partName(parts:Part[],id:string|null){return parts.find(p=>p.id===id)?.title||""}

export default function ChapterManager({username,novel,initialChapters,parts,initialTemplates}:{username:string;novel:{id:string;title:string};initialChapters:Chapter[];parts:Part[];initialTemplates:Template[]}){
  const router=useRouter(),[chapters,setChapters]=useState(initialChapters),[templates,setTemplates]=useState(initialTemplates),[tab,setTab]=useState<"chapters"|"templates">("chapters"),[activeTemplateId,setActiveTemplateId]=useState(initialTemplates[0]?.id??""),[navOpen,setNavOpen]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
  const fileRef=useRef<HTMLInputElement>(null);
  const activeTemplate=templates.find(t=>t.id===activeTemplateId)??templates[0],sample=chapters[0];

  async function patchChapter(id:string,patch:Partial<Chapter>){const current=chapters.find(c=>c.id===id);if(!current)return;setChapters(v=>v.map(c=>c.id===id?{...c,...patch}:c));const r=await fetch(`/api/chapters/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(patch)});if(!r.ok){setChapters(v=>v.map(c=>c.id===id?current:c));setMessage("That chapter change could not be saved.")}}
  async function addChapter(){const r=await fetch("/api/chapters",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({novelId:novel.id})});if(r.ok){const c=await r.json();setChapters(v=>[...v,c])}}
  async function move(id:string,delta:number){const index=chapters.findIndex(c=>c.id===id),target=index+delta;if(index<0||target<0||target>=chapters.length)return;const old=[...chapters],next=[...chapters];[next[index],next[target]]=[next[target],next[index]];next.forEach((c,i)=>c.position=i);setChapters(next);const r=await fetch("/api/chapters/reorder",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({novelId:novel.id,chapters:next.map(c=>({id:c.id,partId:c.partId}))})});if(!r.ok){setChapters(old);setMessage("Chapter order could not be saved.")}}
  async function createTemplate(){const r=await fetch("/api/chapter-templates",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({novelId:novel.id,name:`Template ${templates.length+1}`})});if(!r.ok)return;const t=await r.json() as Template;setTemplates(v=>[...v,t]);setActiveTemplateId(t.id);setTab("templates")}
  function editTemplate(patch:Partial<Template>){if(!activeTemplate)return;setTemplates(v=>v.map(t=>t.id===activeTemplate.id?{...t,...patch}:t))}
  async function saveTemplate(extra?:{makeDefault?:boolean;applyToUnassigned?:boolean}){if(!activeTemplate)return;setSaving(true);setMessage("");const r=await fetch(`/api/chapter-templates/${activeTemplate.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...activeTemplate,...extra})});if(!r.ok){const data=await r.json().catch(()=>({error:"Template could not be saved."}));setMessage(data.error||"Template could not be saved.");setSaving(false);return}const updated=await r.json() as Template;setTemplates(v=>v.map(t=>t.id===updated.id?updated:{...t,isDefault:extra?.makeDefault?false:t.isDefault}));if(extra?.applyToUnassigned)setChapters(v=>v.map(c=>c.templateId?c:{...c,templateId:updated.id}));setMessage(extra?.applyToUnassigned?"Template saved and applied to untemplated chapters.":"Template saved.");setSaving(false)}
  async function uploadHeader(file?:File){if(!file||!activeTemplate)return;setSaving(true);const data=new FormData();data.set("novelId",novel.id);data.set("file",file);const assetResponse=await fetch("/api/assets",{method:"POST",body:data});if(!assetResponse.ok){setMessage("Header image could not be uploaded.");setSaving(false);return}const asset=await assetResponse.json();editTemplate({headerImageAssetId:asset.id,headerImageUrl:asset.url,showImage:true});setSaving(false)}
  async function deleteTemplate(){if(!activeTemplate||activeTemplate.isDefault)return;if(!confirm(`Delete “${activeTemplate.name}”? Chapters using it will fall back to having no template.`))return;const r=await fetch(`/api/chapter-templates/${activeTemplate.id}`,{method:"DELETE"});if(!r.ok){const data=await r.json().catch(()=>({error:"Template could not be deleted."}));setMessage(data.error||"Template could not be deleted.");return}const next=templates.filter(t=>t.id!==activeTemplate.id);setTemplates(next);setChapters(v=>v.map(c=>c.templateId===activeTemplate.id?{...c,templateId:null}:c));setActiveTemplateId(next[0]?.id??"")}
  const ctx=sample?{chapterNumber:1,chapterTitle:sample.title,partTitle:partName(parts,sample.partId),novelTitle:novel.title}:{chapterNumber:1,chapterTitle:"The Chapter Title",partTitle:"Part One",novelTitle:novel.title};
  const templateUsage=useMemo(()=>new Map(templates.map(t=>[t.id,chapters.filter(c=>c.templateId===t.id).length])),[templates,chapters]);

  return <div className="app section-shell"><WorkspaceSectionSidebar username={username} novel={novel} active="manuscript" open={navOpen} onClose={()=>setNavOpen(false)}/>{navOpen&&<button className="scrim" onClick={()=>setNavOpen(false)}/>}<main className="section-main chapter-manager-page">
    <header className="chapter-manager-top"><div className="section-top-left"><button className="menu-button" onClick={()=>setNavOpen(true)}>☰</button></div><div><small>{novel.title}</small><strong>Chapter Manager</strong></div><div className="chapter-manager-actions"><button onClick={()=>router.push(`/workspace/${novel.id}`)}>Open manuscript</button><button className="primary" onClick={addChapter}>＋ Chapter</button></div></header>
    <div className="chapter-manager-tabs"><button className={tab==="chapters"?"active":""} onClick={()=>setTab("chapters")}>Chapters <b>{chapters.length}</b></button><button className={tab==="templates"?"active":""} onClick={()=>setTab("templates")}>Templates <b>{templates.length}</b></button></div>
    {message&&<button className="chapter-manager-message" onClick={()=>setMessage("")}>{message} ×</button>}
    {tab==="chapters"?<section className="chapter-manager-content"><div className="chapter-manager-heading"><div><small>MANUSCRIPT STRUCTURE</small><h1>Chapters</h1><p>Rename, organise and choose how each chapter begins.</p></div><button onClick={createTemplate}>＋ New template</button></div><div className="chapter-table">
      <div className="chapter-table-head"><span>#</span><span>Chapter</span><span>Part</span><span>Status</span><span>Template</span><span>Words</span><span/></div>
      {chapters.map((chapter,index)=><article key={chapter.id}><b>{String(index+1).padStart(2,"0")}</b><input value={chapter.title} onChange={e=>setChapters(v=>v.map(c=>c.id===chapter.id?{...c,title:e.target.value}:c))} onBlur={e=>patchChapter(chapter.id,{title:e.target.value})}/><select value={chapter.partId??""} onChange={e=>{const partId=e.target.value||null;setChapters(v=>v.map(c=>c.id===chapter.id?{...c,partId}:c));fetch("/api/chapters/reorder",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({novelId:novel.id,chapters:chapters.map(c=>({id:c.id,partId:c.id===chapter.id?partId:c.partId}))})})}}><option value="">No Part</option>{parts.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select><select value={chapter.status} onChange={e=>patchChapter(chapter.id,{status:e.target.value})}><option value="DRAFT">Draft</option><option value="REVISE">Revise</option><option value="DONE">Done</option></select><select value={chapter.templateId??""} onChange={e=>patchChapter(chapter.id,{templateId:e.target.value||null})}><option value="">No template</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}{t.isDefault?" · default":""}</option>)}</select><span>{plainWords(chapter.content).toLocaleString()}</span><div><button disabled={index===0} onClick={()=>move(chapter.id,-1)}>↑</button><button disabled={index===chapters.length-1} onClick={()=>move(chapter.id,1)}>↓</button><button onClick={()=>router.push(`/workspace/${novel.id}?chapter=${chapter.id}`)}>Open</button></div></article>)}
    </div></section>:<section className="chapter-template-manager"><aside><div className="template-list-head"><div><small>CHAPTER TEMPLATES</small><strong>{templates.length}</strong></div><button onClick={createTemplate}>＋</button></div>{templates.map(t=><button key={t.id} className={t.id===activeTemplate?.id?"active":""} onClick={()=>setActiveTemplateId(t.id)}><strong>{t.name}</strong><span>{t.isDefault?"Default · ":""}{templateUsage.get(t.id)||0} chapters</span></button>)}{!templates.length&&<div className="template-empty"><strong>No templates yet</strong><span>Create one to build a reusable chapter opening.</span><button onClick={createTemplate}>Create template</button></div>}</aside><main>{activeTemplate?<><div className="template-editor-head"><div><small>TEMPLATE DESIGNER</small><input value={activeTemplate.name} onChange={e=>editTemplate({name:e.target.value})}/><p>Templates stay separate from your prose, so chapter numbers and names can update automatically.</p></div><div>{!activeTemplate.isDefault&&<button onClick={()=>saveTemplate({makeDefault:true})}>Make default</button>}<button className="primary" disabled={saving} onClick={()=>saveTemplate()}>{saving?"Saving…":"Save template"}</button></div></div>
      <div className="template-designer-grid"><section className="template-controls"><label><span>Chapter label</span><input value={activeTemplate.eyebrowPattern} onChange={e=>editTemplate({eyebrowPattern:e.target.value})}/></label><label><span>Title line</span><input value={activeTemplate.titlePattern} onChange={e=>editTemplate({titlePattern:e.target.value})}/></label><div className="template-tags"><small>DYNAMIC TAGS</small>{CHAPTER_TEMPLATE_TAGS.map(tag=><code key={tag}>{tag}</code>)}</div><label className="template-check"><input type="checkbox" checked={activeTemplate.showImage} onChange={e=>editTemplate({showImage:e.target.checked})}/><span>Show a header image</span></label>{activeTemplate.showImage&&<><div className="template-image-row">{activeTemplate.headerImageUrl?<img src={activeTemplate.headerImageUrl} alt=""/>:<div>No image</div>}<div><button onClick={()=>fileRef.current?.click()}>Choose image</button>{activeTemplate.headerImageAssetId&&<button onClick={()=>editTemplate({headerImageAssetId:null,headerImageUrl:null})}>Remove</button>}</div><input ref={fileRef} hidden type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>uploadHeader(e.target.files?.[0])}/></div><label><span>Image width · {activeTemplate.imageWidth}%</span><input type="range" min="20" max="100" value={activeTemplate.imageWidth} onChange={e=>editTemplate({imageWidth:Number(e.target.value)})}/></label><label><span>Image alignment</span><select value={activeTemplate.imageAlign} onChange={e=>editTemplate({imageAlign:e.target.value})}><option value="LEFT">Left</option><option value="CENTER">Centre</option><option value="RIGHT">Right</option></select></label></>}<button className="template-apply" onClick={()=>saveTemplate({applyToUnassigned:true})}>Save + apply to chapters with no template</button>{!activeTemplate.isDefault&&<button className="template-delete" onClick={deleteTemplate}>Delete template</button>}</section>
      <section className="template-preview-panel"><small>LIVE PREVIEW</small><div className="template-paper">{activeTemplate.showImage&&activeTemplate.headerImageUrl&&<img className={`align-${activeTemplate.imageAlign.toLowerCase()}`} style={{width:`${activeTemplate.imageWidth}%`}} src={activeTemplate.headerImageUrl} alt=""/>}<span>{renderChapterTemplateText(activeTemplate.eyebrowPattern,ctx)}</span><h2>{renderChapterTemplateText(activeTemplate.titlePattern,ctx)}</h2><i/><p>The chapter manuscript begins here. The template header is presentation, not copied text, so changing a chapter title or moving its position keeps this opening current.</p></div></section></div>
    </>:<div className="template-empty large"><strong>Create your first chapter template</strong><span>Define the header once, then reuse it across your manuscript.</span><button className="primary" onClick={createTemplate}>＋ Create template</button></div>}</main></section>}
  </main></div>;
}
