"use client";
import {useMemo,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import WorkspaceSectionSidebar from "../../WorkspaceSectionSidebar";
import AssetPicker,{type ProjectAsset} from "../../AssetPicker";
import ChapterTemplateHeader from "../../ChapterTemplateHeader";
import NewChapterDialog,{type NewChapterChoice} from "../../NewChapterDialog";
import {CHAPTER_TEMPLATE_TAGS,type ChapterTemplateDesign} from "@/lib/chapter-template";

type Part={id:string;title:string;position:number};
type Chapter={id:string;partId:string|null;title:string;content:string;summary:string;status:string;position:number;templateId:string|null;headerImageAssetId:string|null};
type Template=ChapterTemplateDesign;

function plainText(html:string){return html.replace(/<style[\s\S]*?<\/style>|<script[\s\S]*?<\/script>/gi," ").replace(/<[^>]*>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g," ").trim()}
function plainWords(html:string){const value=plainText(html);return value?value.split(/\s+/).length:0}
function partName(parts:Part[],id:string|null){return parts.find(p=>p.id===id)?.title||""}
function draftValue(t:Template){const {headerImageUrl,...rest}=t;return JSON.stringify(rest)}
const alignOptions=[["LEFT","Left"],["CENTER","Centre"],["RIGHT","Right"]] as const;
const fontOptions=[["SERIF","Serif"],["SANS","Sans serif"]] as const;

function Segmented({value,onChange}:{value:string;onChange:(v:string)=>void}){return <div className="template-segmented">{alignOptions.map(([v,label])=><button type="button" key={v} className={value===v?"active":""} onClick={()=>onChange(v)}>{label}</button>)}</div>}

export default function ChapterManager({username,novel,initialChapters,parts,initialTemplates}:{username:string;novel:{id:string;title:string};initialChapters:Chapter[];parts:Part[];initialTemplates:Template[]}){
  const router=useRouter(),[chapters,setChapters]=useState(initialChapters),[templates,setTemplates]=useState(initialTemplates),[tab,setTab]=useState<"chapters"|"templates">("chapters"),[activeTemplateId,setActiveTemplateId]=useState(initialTemplates[0]?.id??""),[previewChapterId,setPreviewChapterId]=useState(initialChapters[0]?.id??""),[navOpen,setNavOpen]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[assetPickerOpen,setAssetPickerOpen]=useState(false),[newChapterOpen,setNewChapterOpen]=useState(false);
  const savedDrafts=useRef(new Map(initialTemplates.map(t=>[t.id,draftValue(t)])));
  const activeTemplate=templates.find(t=>t.id===activeTemplateId)??templates[0],previewChapter=chapters.find(c=>c.id===previewChapterId)??chapters[0];
  const dirty=!!activeTemplate&&savedDrafts.current.get(activeTemplate.id)!==draftValue(activeTemplate);

  async function patchChapter(id:string,patch:Partial<Chapter>){const current=chapters.find(c=>c.id===id);if(!current)return;setChapters(v=>v.map(c=>c.id===id?{...c,...patch}:c));const r=await fetch(`/api/chapters/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(patch)});if(!r.ok){setChapters(v=>v.map(c=>c.id===id?current:c));setMessage("That chapter change could not be saved.")}}
  async function addChapter(choice:NewChapterChoice){const r=await fetch("/api/chapters",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({novelId:novel.id,title:choice.title,templateId:choice.templateId})});if(r.ok){const c=await r.json();setChapters(v=>[...v,c]);if(!previewChapterId)setPreviewChapterId(c.id);setNewChapterOpen(false)}}
  async function move(id:string,delta:number){const index=chapters.findIndex(c=>c.id===id),target=index+delta;if(index<0||target<0||target>=chapters.length)return;const old=[...chapters],next=[...chapters];[next[index],next[target]]=[next[target],next[index]];next.forEach((c,i)=>c.position=i);setChapters(next);const r=await fetch("/api/chapters/reorder",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({novelId:novel.id,chapters:next.map(c=>({id:c.id,partId:c.partId}))})});if(!r.ok){setChapters(old);setMessage("Chapter order could not be saved.")}}
  async function createTemplate(){const r=await fetch("/api/chapter-templates",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({novelId:novel.id,name:`Template ${templates.length+1}`})});if(!r.ok)return;const t=await r.json() as Template;savedDrafts.current.set(t.id,draftValue(t));setTemplates(v=>[...v,t]);setActiveTemplateId(t.id);setTab("templates")}
  function editTemplate(patch:Partial<Template>){if(!activeTemplate)return;setTemplates(v=>v.map(t=>t.id===activeTemplate.id?{...t,...patch}:t))}
  function selectTemplate(id:string){if(id===activeTemplateId)return;if(dirty&&!confirm("Discard the unsaved changes to this template?"))return;const current=templates.find(t=>t.id===activeTemplateId),saved=current&&savedDrafts.current.get(current.id);if(current&&saved){const parsed=JSON.parse(saved) as Omit<Template,"headerImageUrl">;setTemplates(v=>v.map(t=>t.id===current.id?{...t,...parsed}:t))}setActiveTemplateId(id);setMessage("")}
  async function saveTemplate(extra?:{makeDefault?:boolean}){if(!activeTemplate)return;setSaving(true);setMessage("");const r=await fetch(`/api/chapter-templates/${activeTemplate.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...activeTemplate,...extra})});if(!r.ok){const data=await r.json().catch(()=>({error:"Template could not be saved."}));setMessage(data.error||"Template could not be saved.");setSaving(false);return}const updated=await r.json() as Template;savedDrafts.current.set(updated.id,draftValue(updated));setTemplates(v=>v.map(t=>t.id===updated.id?updated:{...t,isDefault:extra?.makeDefault?false:t.isDefault}));setMessage("Template saved.");setSaving(false)}
  function chooseHeaderAsset(asset:ProjectAsset){editTemplate({headerImageAssetId:asset.id,headerImageUrl:asset.url,showImage:true});setAssetPickerOpen(false)}
  async function deleteTemplate(){if(!activeTemplate)return;if(!confirm(`Delete “${activeTemplate.name}”? Existing chapters using it will keep their prose but lose this template header.`))return;const r=await fetch(`/api/chapter-templates/${activeTemplate.id}`,{method:"DELETE"});if(!r.ok){const data=await r.json().catch(()=>({error:"Template could not be deleted."}));setMessage(data.error||"Template could not be deleted.");return}savedDrafts.current.delete(activeTemplate.id);const result=await r.json() as {nextDefaultId:string|null};const next=templates.filter(t=>t.id!==activeTemplate.id).map(t=>({...t,isDefault:t.id===result.nextDefaultId}));setTemplates(next);setChapters(v=>v.map(c=>c.templateId===activeTemplate.id?{...c,templateId:null}:c));setActiveTemplateId(next[0]?.id??"")}
  const previewIndex=Math.max(0,chapters.findIndex(c=>c.id===previewChapter?.id));
  const ctx={chapterNumber:previewIndex+1,chapterTitle:previewChapter?.title||"The Chapter Title",partTitle:partName(parts,previewChapter?.partId??null)||"Part One",novelTitle:novel.title};
  const previewBody=plainText(previewChapter?.content||"")||"The chapter manuscript begins here. This is a live representation of the opening page, so you can shape the header against real manuscript text before saving the template.";
  const templateUsage=useMemo(()=>new Map(templates.map(t=>[t.id,chapters.filter(c=>c.templateId===t.id).length])),[templates,chapters]);

  return <div className="app section-shell"><WorkspaceSectionSidebar username={username} novel={novel} active="manuscript" open={navOpen} onClose={()=>setNavOpen(false)}/>{navOpen&&<button className="scrim" onClick={()=>setNavOpen(false)}/>}<main className="section-main chapter-manager-page">
    <header className="chapter-manager-top"><div className="section-top-left"><button className="menu-button" onClick={()=>setNavOpen(true)}>☰</button></div><div><small>{novel.title}</small><strong>Chapter Manager</strong></div><div className="chapter-manager-actions"><button onClick={()=>router.push(`/workspace/${novel.id}`)}>Open manuscript</button><button className="primary" onClick={()=>setNewChapterOpen(true)}>＋ Chapter</button></div></header>
    <div className="chapter-manager-tabs"><button className={tab==="chapters"?"active":""} onClick={()=>setTab("chapters")}>Chapters <b>{chapters.length}</b></button><button className={tab==="templates"?"active":""} onClick={()=>setTab("templates")}>Templates <b>{templates.length}</b></button></div>
    {message&&<button className="chapter-manager-message" onClick={()=>setMessage("")}>{message} ×</button>}
    {tab==="chapters"?<section className="chapter-manager-content"><div className="chapter-manager-heading"><div><small>MANUSCRIPT STRUCTURE</small><h1>Chapters</h1><p>Rename, organise and choose how each chapter begins.</p></div><button onClick={createTemplate}>＋ New template</button></div><div className="chapter-table"><div className="chapter-table-head"><span>#</span><span>Chapter</span><span>Part</span><span>Status</span><span>Template</span><span>Words</span><span/></div>{chapters.map((chapter,index)=><article key={chapter.id}><b>{String(index+1).padStart(2,"0")}</b><input value={chapter.title} onChange={e=>setChapters(v=>v.map(c=>c.id===chapter.id?{...c,title:e.target.value}:c))} onBlur={e=>patchChapter(chapter.id,{title:e.target.value})}/><select value={chapter.partId??""} onChange={e=>{const partId=e.target.value||null;setChapters(v=>v.map(c=>c.id===chapter.id?{...c,partId}:c));fetch("/api/chapters/reorder",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({novelId:novel.id,chapters:chapters.map(c=>({id:c.id,partId:c.id===chapter.id?partId:c.partId}))})})}}><option value="">No Part</option>{parts.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select><select value={chapter.status} onChange={e=>patchChapter(chapter.id,{status:e.target.value})}><option value="DRAFT">Draft</option><option value="REVISE">Revise</option><option value="DONE">Done</option></select><select value={chapter.templateId??""} onChange={e=>patchChapter(chapter.id,{templateId:e.target.value||null})}><option value="">No template</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}{t.isDefault?" · default":""}</option>)}</select><span>{plainWords(chapter.content).toLocaleString()}</span><div><button disabled={index===0} onClick={()=>move(chapter.id,-1)}>↑</button><button disabled={index===chapters.length-1} onClick={()=>move(chapter.id,1)}>↓</button><button onClick={()=>router.push(`/workspace/${novel.id}?chapter=${chapter.id}`)}>Open</button></div></article>)}</div></section>
    :<section className="chapter-template-manager"><aside><div className="template-list-head"><div><small>CHAPTER TEMPLATES</small><strong>{templates.length}</strong></div><button onClick={createTemplate}>＋</button></div>{templates.map(t=><button key={t.id} className={t.id===activeTemplate?.id?"active":""} onClick={()=>selectTemplate(t.id)}><strong>{t.name}</strong><span>{t.isDefault?"Suggested · ":""}{templateUsage.get(t.id)||0} chapters</span></button>)}{!templates.length&&<div className="template-empty"><strong>No templates yet</strong><span>Create one to build a reusable chapter opening.</span><button onClick={createTemplate}>Create template</button></div>}</aside><main>{activeTemplate?<>
      <div className="template-editor-head"><div><small>LIVE CHAPTER DESIGNER</small><input value={activeTemplate.name} onChange={e=>editTemplate({name:e.target.value})}/><p>Design the opening against a real chapter. Nothing changes in the novel until you save the template.</p></div><div>{dirty&&<span className="template-unsaved">Unsaved changes</span>}{!activeTemplate.isDefault&&<button onClick={()=>saveTemplate({makeDefault:true})}>Make suggested</button>}<button className="primary" disabled={saving||!dirty} onClick={()=>saveTemplate()}>{saving?"Saving…":dirty?"Save template":"Saved"}</button></div></div>
      <div className="template-studio">
        <section className="template-live-stage"><div className="template-preview-bar"><span>Preview chapter</span><select value={previewChapter?.id||""} onChange={e=>setPreviewChapterId(e.target.value)}>{chapters.map((c,i)=><option key={c.id} value={c.id}>{i+1}. {c.title}</option>)}</select><button onClick={()=>router.push(`/workspace/${novel.id}?chapter=${previewChapter?.id||""}`)}>Open live chapter</button></div><div className="template-live-paper"><ChapterTemplateHeader template={activeTemplate} context={ctx} imageUrl={activeTemplate.headerImageUrl}/><div className="template-live-manuscript"><p>{previewBody.slice(0,900)}{previewBody.length>900?"…":""}</p><p>Another paragraph shows how the opening settles into the normal manuscript flow.</p></div></div></section>
        <aside className="template-inspector">
          <section><h3>Content</h3><label><span>Chapter label</span><input value={activeTemplate.eyebrowPattern} onChange={e=>editTemplate({eyebrowPattern:e.target.value})}/></label><label><span>Title line</span><input value={activeTemplate.titlePattern} onChange={e=>editTemplate({titlePattern:e.target.value})}/></label><div className="template-tags"><small>DYNAMIC TAGS</small>{CHAPTER_TEMPLATE_TAGS.map(tag=><code key={tag}>{tag}</code>)}</div></section>
          <section><h3>Chapter label</h3><label><span>Alignment</span><Segmented value={activeTemplate.labelAlign} onChange={labelAlign=>editTemplate({labelAlign})}/></label><div className="template-control-pair"><label><span>Font</span><select value={activeTemplate.labelFont} onChange={e=>editTemplate({labelFont:e.target.value})}>{fontOptions.map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><label><span>Weight</span><select value={activeTemplate.labelWeight} onChange={e=>editTemplate({labelWeight:Number(e.target.value)})}>{[400,500,600,700,800,900].map(v=><option key={v} value={v}>{v}</option>)}</select></label></div><div className="template-control-pair"><label><span>Case</span><select value={activeTemplate.labelCase} onChange={e=>editTemplate({labelCase:e.target.value})}><option value="NORMAL">As typed</option><option value="UPPER">UPPERCASE</option><option value="LOWER">lowercase</option></select></label><label><span>Colour</span><span className="template-colour"><input type="color" value={activeTemplate.labelColor||"#0284C7"} onChange={e=>editTemplate({labelColor:e.target.value})}/><button type="button" onClick={()=>editTemplate({labelColor:""})}>Theme</button></span></label></div><label><span>Size · {activeTemplate.labelSize}px</span><input type="range" min="8" max="28" value={activeTemplate.labelSize} onChange={e=>editTemplate({labelSize:Number(e.target.value)})}/></label><label><span>Space after · {activeTemplate.labelSpacing}px</span><input type="range" min="0" max="80" value={activeTemplate.labelSpacing} onChange={e=>editTemplate({labelSpacing:Number(e.target.value)})}/></label></section>
          <section><h3>Chapter title</h3><label><span>Alignment</span><Segmented value={activeTemplate.titleAlign} onChange={titleAlign=>editTemplate({titleAlign})}/></label><div className="template-control-pair"><label><span>Font</span><select value={activeTemplate.titleFont} onChange={e=>editTemplate({titleFont:e.target.value})}>{fontOptions.map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><label><span>Weight</span><select value={activeTemplate.titleWeight} onChange={e=>editTemplate({titleWeight:Number(e.target.value)})}>{[400,500,600,700,800,900].map(v=><option key={v} value={v}>{v}</option>)}</select></label></div><div className="template-control-pair"><label><span>Case</span><select value={activeTemplate.titleCase} onChange={e=>editTemplate({titleCase:e.target.value})}><option value="NORMAL">As typed</option><option value="UPPER">UPPERCASE</option><option value="LOWER">lowercase</option></select></label><label><span>Colour</span><span className="template-colour"><input type="color" value={activeTemplate.titleColor||"#202838"} onChange={e=>editTemplate({titleColor:e.target.value})}/><button type="button" onClick={()=>editTemplate({titleColor:""})}>Theme</button></span></label></div><label><span>Size · {activeTemplate.titleSize}px</span><input type="range" min="20" max="80" value={activeTemplate.titleSize} onChange={e=>editTemplate({titleSize:Number(e.target.value)})}/></label><label><span>Space after · {activeTemplate.titleSpacing}px</span><input type="range" min="0" max="100" value={activeTemplate.titleSpacing} onChange={e=>editTemplate({titleSpacing:Number(e.target.value)})}/></label></section>
          <section><h3>Divider</h3><label className="template-check"><input type="checkbox" checked={activeTemplate.showDivider} onChange={e=>editTemplate({showDivider:e.target.checked})}/><span>Show divider below title</span></label>{activeTemplate.showDivider&&<><label><span>Width · {activeTemplate.dividerWidth}%</span><input type="range" min="3" max="100" value={activeTemplate.dividerWidth} onChange={e=>editTemplate({dividerWidth:Number(e.target.value)})}/></label><label><span>Thickness · {activeTemplate.dividerThickness}px</span><input type="range" min="1" max="5" value={activeTemplate.dividerThickness} onChange={e=>editTemplate({dividerThickness:Number(e.target.value)})}/></label></>}</section>
          <section><h3>Header image</h3><label className="template-check"><input type="checkbox" checked={activeTemplate.showImage} onChange={e=>editTemplate({showImage:e.target.checked})}/><span>Show image</span></label>{activeTemplate.showImage&&<><div className="template-image-row">{activeTemplate.headerImageUrl?<img src={activeTemplate.headerImageUrl} alt=""/>:<div>No image</div>}<div><button onClick={()=>setAssetPickerOpen(true)}>Choose image</button>{activeTemplate.headerImageAssetId&&<button onClick={()=>editTemplate({headerImageAssetId:null,headerImageUrl:null})}>Remove</button>}</div></div><label><span>Position</span><select value={activeTemplate.imagePosition} onChange={e=>editTemplate({imagePosition:e.target.value})}><option value="BEFORE_LABEL">Before chapter label</option><option value="BETWEEN_LABEL_TITLE">Between label and title</option><option value="AFTER_TITLE">After title</option><option value="AFTER_DIVIDER">After divider</option></select></label><label><span>Alignment</span><Segmented value={activeTemplate.imageAlign} onChange={imageAlign=>editTemplate({imageAlign})}/></label><label><span>Width · {activeTemplate.imageWidth}%</span><input type="range" min="20" max="100" value={activeTemplate.imageWidth} onChange={e=>editTemplate({imageWidth:Number(e.target.value)})}/></label><label><span>Space after · {activeTemplate.imageSpacing}px</span><input type="range" min="0" max="100" value={activeTemplate.imageSpacing} onChange={e=>editTemplate({imageSpacing:Number(e.target.value)})}/></label></>}</section>
          <section><h3>Page spacing</h3><label><span>Space above header · {activeTemplate.headerPaddingTop}px</span><input type="range" min="0" max="180" value={activeTemplate.headerPaddingTop} onChange={e=>editTemplate({headerPaddingTop:Number(e.target.value)})}/></label><label><span>Space before manuscript · {activeTemplate.headerPaddingBottom}px</span><input type="range" min="0" max="180" value={activeTemplate.headerPaddingBottom} onChange={e=>editTemplate({headerPaddingBottom:Number(e.target.value)})}/></label></section>
          <section className="template-inspector-actions"><p className="template-new-chapter-note">Templates are chosen when a new chapter is created. Saving this template never changes existing chapters.</p><button className="template-delete" onClick={deleteTemplate}>Delete template</button></section>
        </aside>
      </div>
    </>:<div className="template-empty large"><strong>Create your first chapter template</strong><span>Design the chapter opening as it will actually appear in the manuscript.</span><button className="primary" onClick={createTemplate}>＋ Create template</button></div>}</main></section>}
    {newChapterOpen&&<NewChapterDialog novelTitle={novel.title} templates={templates} onClose={()=>setNewChapterOpen(false)} onCreate={addChapter}/>} {assetPickerOpen&&<AssetPicker novelId={novel.id} title="Choose template header image" onClose={()=>setAssetPickerOpen(false)} onSelect={chooseHeaderAsset}/>}
  </main></div>;
}
