import {randomUUID} from "node:crypto";
import {NextRequest,NextResponse} from "next/server";
import {query} from "@/lib/db";
import {encryptSetting} from "@/lib/secret-box";
import {consumeCloudOAuthState,exchangeCloudCode,type CloudProvider} from "@/lib/cloud-oauth";
const supported=new Set<CloudProvider>(["googleDrive","oneDrive"]);
function settingsUrl(request:NextRequest,key:string,value:string){const url=new URL("/settings",request.url);url.searchParams.set(key,value);return url}
export async function GET(request:NextRequest,{params}:{params:Promise<{provider:string}>}){const {provider:raw}=await params,provider=raw as CloudProvider;if(!supported.has(provider))return NextResponse.redirect(settingsUrl(request,"backupError","unsupported"));const state=request.nextUrl.searchParams.get("state")||"",code=request.nextUrl.searchParams.get("code")||"",oauthError=request.nextUrl.searchParams.get("error");if(oauthError||!state||!code)return NextResponse.redirect(settingsUrl(request,"backupError",oauthError||"missing-code"));const saved=await consumeCloudOAuthState(state,provider);if(!saved)return NextResponse.redirect(settingsUrl(request,"backupError","expired-state"));try{const token=await exchangeCloudCode(provider,request,code,saved.verifier);if(!token.refresh_token)return NextResponse.redirect(settingsUrl(request,"backupError","missing-refresh-token"));await query(`INSERT INTO "BackupDestination" ("id","userId","provider","enabled","folder","accountLabel","providerAccountId","refreshTokenEncrypted","connectedAt","createdAt","updatedAt") VALUES ($1,$2,$3,true,'/Sögur Forge',$4,$5,$6,NOW(),NOW(),NOW()) ON CONFLICT ("userId","provider") DO UPDATE SET "enabled"=true,"accountLabel"=$4,"providerAccountId"=$5,"refreshTokenEncrypted"=$6,"connectedAt"=NOW(),"lastBackupError"='',"updatedAt"=NOW()`,[randomUUID(),saved.userId,provider,token.accountLabel||"",token.providerAccountId||"",encryptSetting(token.refresh_token)]);return NextResponse.redirect(settingsUrl(request,"backupConnected",provider))}catch(error){console.error("Cloud OAuth callback failed",provider,error);return NextResponse.redirect(settingsUrl(request,"backupError",`${provider}-connect-failed`))}
}
