"use client";
import {FormEvent,useState} from "react";
import {useRouter} from "next/navigation";
import type {BackupProviderAvailability,BackupProviderId} from "@/lib/backup-providers";
import type {UserBackupDestination} from "@/lib/user-backups";
type Profile={username:string;email:string;role:string;emailVerifiedAt:string|null;createdAt:string};
const providerNames:Record<string,string>={googleDrive:"Google Drive",oneDrive:"OneDrive",dropbox:"Dropbox"};
export default function SettingsClient({profile,backupMethods,initialDestinations,cloudNotice}:{profile:Profile;backupMethods:BackupProviderAvailability;initialDestinations:UserBackupDestination[];cloudNotice:{connected:string;error:string}}){
 const router=useRouter(),[busy,setBusy]=useState(""),[message,setMessage]=useState(cloudNotice.connected?`${providerNames[cloudNotice.connected]||"Cloud account"} connected.`:cloudNotice.error?"Cloud account connection was not completed." :""),[error,setError]=useState(""),[destinations,setDestinations]=useState(initialDestinations);
 async function password(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy("password");setMessage("");setError("");const f=new FormData(event.currentTarget),r=await fetch("/api/account/password",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword:f.get("currentPassword"),newPassword:f.get("newPassword")})}),d=await r.json();if(!r.ok){setError(d.error||"Password could not be changed.");setBusy("");return}setMessage("Password changed. All sessions have been signed out.");setTimeout(()=>{window.location.href="/"},900)}
 async function saveDestination(provider:BackupProviderId,patch:Partial<UserBackupDestination>){const current=destinations.find(item=>item.provider===provider)!;const next={...current,...patch};setDestinations(v=>v.map(item=>item.provider===provider?next:item));const r=await fetch("/api/account/backup-settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)}),d=await r.json();if(!r.ok){setDestinations(v=>v.map(item=>item.provider===provider?current:item));setMessage(d.error||"Backup setting could not be saved.");return}setDestinations(v=>v.map(item=>item.provider===provider?{...item,...d}:item));setMessage("Backup location saved.")}
 async function backupNow(provider:"googleDrive"|"oneDrive"){setBusy(`backup:${provider}`);setMessage("");const r=await fetch(`/api/account/cloud-backups/${provider}`,{method:"POST"}),d=await r.json();if(r.ok){setDestinations(v=>v.map(item=>item.provider===provider?{...item,lastBackupAt:d.backedUpAt,lastBackupError:""}:item));setMessage(`Backup uploaded to ${providerNames[provider]}.`)}else{setDestinations(v=>v.map(item=>item.provider===provider?{...item,lastBackupError:d.error||"Backup failed."}:item));setMessage(d.error||"Cloud backup failed.")}setBusy("")}
 async function disconnect(provider:"googleDrive"|"oneDrive"){if(!confirm(`Disconnect ${providerNames[provider]} from Sögur Forge?`))return;setBusy(`disconnect:${provider}`);const r=await fetch(`/api/account/cloud-backups/${provider}`,{method:"DELETE"});if(r.ok){setDestinations(v=>v.map(item=>item.provider===provider?{...item,connected:false,enabled:false,accountLabel:"",connectedAt:null,lastBackupError:""}:item));setMessage(`${providerNames[provider]} disconnected.`)}else setMessage("The cloud account could not be disconnected.");setBusy("")}
 const cards=[
  {provider:"googleDrive" as const,name:"Google Drive",method:backupMethods.googleDrive},
  {provider:"oneDrive" as const,name:"OneDrive",method:backupMethods.oneDrive}
 ].filter(item=>item.method.enabled);
 return <main className="settings-shell"><header className="settings-top"><div><button onClick={()=>router.push("/workspace")}>← Library</button><div><small>ACCOUNT</small><strong>Settings</strong></div></div>{profile.role==="ADMIN"&&<button onClick={()=>router.push("/admin")}>Admin controls</button>}</header><section className="settings-main"><div className="settings-heading"><small>YOUR ACCOUNT</small><h1>Settings & data</h1><p>Manage account security, data ownership and your personal backup destinations.</p></div>{message&&<button className="settings-message" onClick={()=>setMessage("")}>{message} ×</button>}<div className="settings-grid">
 <section className="settings-card"><div className="settings-card-head"><div><small>PROFILE</small><h2>{profile.username}</h2></div><span className={profile.emailVerifiedAt?"status-good":"status-warn"}>{profile.emailVerifiedAt?"Verified":"Unverified"}</span></div><div className="settings-fact"><span>Email</span><strong>{profile.email}</strong></div><div className="settings-fact"><span>Account type</span><strong>{profile.role==="ADMIN"?"Administrator":"User"}</strong></div><div className="settings-fact"><span>Created</span><strong>{new Date(profile.createdAt).toLocaleDateString()}</strong></div></section>
 <section className="settings-card"><div className="settings-card-head"><div><small>SECURITY</small><h2>Change password</h2></div></div><form className="settings-form" onSubmit={password}><label><span>Current password</span><input type="password" name="currentPassword" required/></label><label><span>New password</span><input type="password" name="newPassword" minLength={12} required/></label>{error&&<p className="settings-warning">{error}</p>}<button className="primary" disabled={busy==="password"}>{busy==="password"?"Changing…":"Change password & sign out everywhere"}</button></form></section>
 <section className="settings-card settings-card-wide"><div className="settings-card-head"><div><small>YOUR DATA</small><h2>Export & backup</h2></div></div><p className="settings-copy">The clean data export is always yours to download. Backup methods can be restricted by the server administrator.</p><div className="data-actions"><a href="/api/account/export"><strong>Download all my data</strong><span>Readable ZIP containing your account data, writing, Story Bible and assets.</span><b>Export ZIP ↓</b></a>{backupMethods.download.enabled&&<a href="/api/account/backup"><strong>Download a backup</strong><span>Provider-neutral backup ZIP for safekeeping or later restore.</span><b>Backup ZIP ↓</b></a>}</div></section>
 <section className="settings-card settings-card-wide"><div className="settings-card-head"><div><small>CLOUD BACKUPS</small><h2>My backup locations</h2></div></div>{cards.length?<><p className="settings-copy">Connect your own account once, choose a Sögur Forge subfolder, then use Back up now. The administrator only decides which providers are permitted.</p><div className="cloud-account-grid">{cards.map(card=>{const destination=destinations.find(item=>item.provider===card.provider)!;return <article key={card.provider} className={destination.connected?"connected":""}><div className="cloud-account-head"><div><strong>{card.name}</strong><span>{destination.connected?(destination.accountLabel||"Connected account"):card.method.configured?"Ready to connect":"Server OAuth setup required"}</span></div><b>{destination.connected?"Connected ✓":"Not connected"}</b></div>{destination.connected?<><label className="backup-folder"><span>Backup subfolder</span><input value={destination.folder} onChange={e=>setDestinations(v=>v.map(item=>item.provider===card.provider?{...item,folder:e.target.value}:item))} onBlur={e=>saveDestination(card.provider,{folder:e.target.value})}/></label><label className="settings-toggle compact"><div><strong>Use for backups</strong><span>Keep this destination active.</span></div><input type="checkbox" checked={destination.enabled} onChange={e=>saveDestination(card.provider,{enabled:e.target.checked})}/></label>{destination.lastBackupAt&&<p className="cloud-last">Last backup: {new Date(destination.lastBackupAt).toLocaleString()}</p>}{destination.lastBackupError&&<p className="settings-warning">{destination.lastBackupError}</p>}<div className="cloud-account-actions"><button onClick={()=>disconnect(card.provider)} disabled={!!busy}>Disconnect</button><button className="primary" onClick={()=>backupNow(card.provider)} disabled={!!busy||!destination.enabled}>{busy===`backup:${card.provider}`?"Backing up…":"Back up now"}</button></div></>:card.method.configured?<a className="cloud-connect" href={`/api/account/cloud-backups/${card.provider}/connect`}>Connect {card.name}</a>:<p className="settings-muted">The server owner must configure the {card.name} OAuth application before accounts can be linked.</p>}</article>})}</div><p className="settings-muted">Sögur Forge requests narrow file access and stores your refresh token encrypted on this server. Dropbox will follow after Google Drive and OneDrive are proven.</p></>:<p className="settings-muted">Your administrator has not enabled Google Drive or OneDrive backups on this server.</p>}</section>
 </div></section></main>
}
