"use client";
import {FormEvent,useState} from "react";
import {useRouter} from "next/navigation";
import type {BackupProviderAvailability,BackupProviderId} from "@/lib/backup-providers";
import type {UserBackupDestination} from "@/lib/user-backups";
type Profile={username:string;email:string;role:string;emailVerifiedAt:string|null;createdAt:string};
export default function SettingsClient({profile,backupMethods,initialDestinations}:{profile:Profile;backupMethods:BackupProviderAvailability;initialDestinations:UserBackupDestination[]}){const router=useRouter(),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[destinations,setDestinations]=useState(initialDestinations);
async function password(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");setError("");const f=new FormData(event.currentTarget),r=await fetch("/api/account/password",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword:f.get("currentPassword"),newPassword:f.get("newPassword")})}),d=await r.json();if(!r.ok){setError(d.error||"Password could not be changed.");setBusy(false);return}setMessage("Password changed. All sessions have been signed out.");setTimeout(()=>{window.location.href="/"},900)}
async function saveDestination(provider:BackupProviderId,patch:Partial<UserBackupDestination>){const current=destinations.find(item=>item.provider===provider)!;const next={...current,...patch};setDestinations(v=>v.map(item=>item.provider===provider?next:item));const r=await fetch("/api/account/backup-settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)}),d=await r.json();if(!r.ok){setDestinations(v=>v.map(item=>item.provider===provider?current:item));setMessage(d.error||"Backup setting could not be saved.");return}setDestinations(v=>v.map(item=>item.provider===provider?d:item));setMessage("Backup location saved.")}
const cards=[{provider:"dropbox" as const,name:"Dropbox",allowed:backupMethods.dropbox.enabled},{provider:"googleDrive" as const,name:"Google Drive",allowed:backupMethods.googleDrive.enabled},{provider:"oneDrive" as const,name:"OneDrive",allowed:backupMethods.oneDrive.enabled}].filter(item=>item.allowed);
return <main className="settings-shell"><header className="settings-top"><div><button onClick={()=>router.push("/workspace")}>← Library</button><div><small>ACCOUNT</small><strong>Settings</strong></div></div>{profile.role==="ADMIN"&&<button onClick={()=>router.push("/admin")}>Admin controls</button>}</header><section className="settings-main"><div className="settings-heading"><small>YOUR ACCOUNT</small><h1>Settings & data</h1><p>Manage account security, data ownership and your personal backup destinations.</p></div>{message&&<button className="settings-message" onClick={()=>setMessage("")}>{message} ×</button>}<div className="settings-grid">
<section className="settings-card"><div className="settings-card-head"><div><small>PROFILE</small><h2>{profile.username}</h2></div><span className={profile.emailVerifiedAt?"status-good":"status-warn"}>{profile.emailVerifiedAt?"Verified":"Unverified"}</span></div><div className="settings-fact"><span>Email</span><strong>{profile.email}</strong></div><div className="settings-fact"><span>Account type</span><strong>{profile.role==="ADMIN"?"Administrator":"User"}</strong></div><div className="settings-fact"><span>Created</span><strong>{new Date(profile.createdAt).toLocaleDateString()}</strong></div></section>
<section className="settings-card"><div className="settings-card-head"><div><small>SECURITY</small><h2>Change password</h2></div></div><form className="settings-form" onSubmit={password}><label><span>Current password</span><input type="password" name="currentPassword" required/></label><label><span>New password</span><input type="password" name="newPassword" minLength={12} required/></label>{error&&<p className="settings-warning">{error}</p>}<button className="primary" disabled={busy}>{busy?"Changing…":"Change password & sign out everywhere"}</button></form></section>
<section className="settings-card settings-card-wide"><div className="settings-card-head"><div><small>YOUR DATA</small><h2>Export & backup</h2></div></div><p className="settings-copy">The clean data export is always yours to download. Backup methods can be restricted by the server administrator.</p><div className="data-actions"><a href="/api/account/export"><strong>Download all my data</strong><span>Readable ZIP containing your account data, writing, Story Bible and assets.</span><b>Export ZIP ↓</b></a>{backupMethods.download.enabled&&<a href="/api/account/backup"><strong>Download a backup</strong><span>Provider-neutral backup ZIP for safekeeping or later restore.</span><b>Backup ZIP ↓</b></a>}</div></section>
<section className="settings-card settings-card-wide"><div className="settings-card-head"><div><small>CLOUD BACKUPS</small><h2>My backup locations</h2></div></div>{cards.length?<><p className="settings-copy">These are your destinations, not the administrator's. Choose the providers you want to use and the folder where Sögur Forge should place your backups.</p><div className="user-backup-destinations">{cards.map(card=>{const destination=destinations.find(item=>item.provider===card.provider)!;return <article key={card.provider}><div><strong>{card.name}</strong><span>Personal cloud destination</span></div><label><span>Use this destination</span><input type="checkbox" checked={destination.enabled} onChange={e=>saveDestination(card.provider,{enabled:e.target.checked})}/></label><label className="backup-folder"><span>Backup folder</span><input value={destination.folder} onChange={e=>setDestinations(v=>v.map(item=>item.provider===card.provider?{...item,folder:e.target.value}:item))} onBlur={e=>saveDestination(card.provider,{folder:e.target.value})}/></label><button disabled title="Provider account authorisation is the next cloud-backup step">Connect my {card.name} account · coming next</button></article>})}</div><p className="settings-muted">Your chosen locations are stored per account. OAuth connection and scheduled upload will plug into these saved destinations next.</p></>:<p className="settings-muted">Your administrator has not enabled any cloud backup providers on this server.</p>}</section>
</div></section></main>}
