import {randomUUID} from "node:crypto";
import {NextRequest,NextResponse} from "next/server";
import {currentUser} from "@/lib/auth/session";
import {requireSameOrigin} from "@/lib/auth/request";
import {query} from "@/lib/db";
import {getSiteSettings} from "@/lib/site-settings";
import {providerAllowed,type BackupProviderId} from "@/lib/backup-providers";
const providers=new Set<BackupProviderId>(["dropbox","googleDrive","oneDrive"]);
export async function PATCH(request:NextRequest){if(!requireSameOrigin(request))return NextResponse.json({error:"Invalid origin"},{status:403});const user=await currentUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const body=await request.json(),provider=String(body.provider||"") as BackupProviderId;if(!providers.has(provider))return NextResponse.json({error:"Unknown provider"},{status:400});const settings=await getSiteSettings();if(!providerAllowed(settings,provider))return NextResponse.json({error:"This backup provider has been disabled by the administrator."},{status:403});const folder=String(body.folder??"/Sögur Forge").trim().slice(0,500)||"/Sögur Forge",enabled=!!body.enabled;const result=await query<{provider:string;enabled:boolean;folder:string;accountLabel:string;refreshTokenEncrypted:string;connectedAt:Date|null;lastBackupAt:Date|null;lastBackupError:string}>(`INSERT INTO "BackupDestination" ("id","userId","provider","enabled","folder","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,NOW(),NOW()) ON CONFLICT ("userId","provider") DO UPDATE SET "enabled"=$4,"folder"=$5,"updatedAt"=NOW() RETURNING "provider","enabled","folder","accountLabel","refreshTokenEncrypted","connectedAt","lastBackupAt","lastBackupError"`,[randomUUID(),user.id,provider,enabled,folder]);const row=result.rows[0];return NextResponse.json({provider:row.provider,enabled:row.enabled,folder:row.folder,accountLabel:row.accountLabel,connected:!!row.refreshTokenEncrypted,connectedAt:row.connectedAt?.toISOString()??null,lastBackupAt:row.lastBackupAt?.toISOString()??null,lastBackupError:row.lastBackupError})}
