"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import RichEditor,{plainText} from "./RichEditor";
import {combineSceneContents} from "@/lib/scenes";

export type SceneRecord={id:string;chapterId:string;povCharacterId:string|null;title:string;content:string;summary:string;goal:string;conflict:string;outcome:string;location:string;status:string;position:number};
type CharacterOption={id:string;name:string};
type SaveState="saved"|"saving"|"error";

export default function SceneEditor({chapterId,chapterContent,novelId,focus,onChapterContentChange,onAggregateSaved,onSaveStateChange,onCreateLinkedNote,focusAnchorId,onAnchorClick}:{chapterId:string;chapterContent:string;novelId:string;focus:boolean;onChapterContentChange:(content:string)=>void;onAggregateSaved:(content:string)=>void;onSaveStateChange:(state:SaveState)=>void;onCreateLinkedNote?:(quote:string,anchorId:string)=>Promise<boolean>;focusAnchorId?:string|null;onAnchorClick?:(anchorId:string)=>void}){
  const [scenes,setScenes]=useState<SceneRecord[]>([]),[characters,setCharacters]=useState<CharacterOption[]>([]),[loading,setLoading]=useState(true),[activeId,setActiveId]=useState(""),[dragging,setDragging]=useState<string|null>(null),[drop,setDrop]=useState<{id:string;after:boolean}|null>(null),[error,setError]=useState("");
  const timers=useRef(new Map<string,ReturnType<typeof setTimeout>>()),scenesRef=useRef<SceneRecord[]>([]);
  useEffect(()=>{scenesRef.current=scenes},[scenes]);
  useEffect(()=>{let live=true;setLoading(true);setError("");fetch(`/api/scenes?chapterId=${chapterId}`,{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(data=>{if(!live)return;const next=(data.scenes||[]) as SceneRecord[];setScenes(next);setCharacters(data.characters||[]);setActiveId(next[0]?.id||"");setLoading(false)}).catch(()=>{if(live){setLoading(false);setError("Scenes could not be loaded.")}});return()=>{live=false;flushPending(true)}},[chapterId]);
  useEffect(()=>{if(!focusAnchorId)return;const scene=scenes.find(item=>item.content.includes(focusAnchorId));if(scene)setActiveId(scene.id)},[focusAnchorId,scenes]);

  const ordered=useMemo(()=>[...scenes].sort((a,b)=>a.position-b.position),[scenes]),active=ordered.find(scene=>scene.id===activeId)??ordered[0],activeIndex=Math.max(0,ordered.findIndex(scene=>scene.id===active?.id));
  const sceneWords=active?(()=>{const text=plainText(active.content).trim();return text?text.split(/\s+/).length:0})():0;

  function preview(next:SceneRecord[]){setScenes(next);onChapterContentChange(combineSceneContents([...next].sort((a,b)=>a.position-b.position).map(scene=>scene.content)))}
  async function savePatch(id:string,patch:Partial<SceneRecord>,keepalive=false){onSaveStateChange("saving");try{const r=await fetch(`/api/scenes/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(patch),keepalive});if(!r.ok)throw new Error();const data=await r.json();if(data.scenes)setScenes(data.scenes);if(typeof data.aggregateContent==="string"){onChapterContentChange(data.aggregateContent);onAggregateSaved(data.aggregateContent)}onSaveStateChange("saved");return true}catch{onSaveStateChange("error");setError("Scene changes could not be saved.");return false}}
  function schedulePatch(id:string,patch:Partial<SceneRecord>){const old=timers.current.get(id);if(old)clearTimeout(old);onSaveStateChange("saving");timers.current.set(id,setTimeout(()=>{timers.current.delete(id);savePatch(id,patch)},650))}
  function edit(patch:Partial<SceneRecord>,immediate=false){if(!active)return;const next=scenes.map(scene=>scene.id===active.id?{...scene,...patch}:scene);preview(next);if(immediate)savePatch(active.id,patch);else schedulePatch(active.id,patch)}
  function flushPending(keepalive=false){for(const [id,timer] of timers.current){clearTimeout(timer);const scene=scenesRef.current.find(item=>item.id===id);if(scene)savePatch(id,{title:scene.title,content:scene.content,summary:scene.summary,goal:scene.goal,conflict:scene.conflict,outcome:scene.outcome,location:scene.location,status:scene.status,povCharacterId:scene.povCharacterId},keepalive)}timers.current.clear()}
  async function flushScene(id:string){const timer=timers.current.get(id);if(!timer)return true;clearTimeout(timer);timers.current.delete(id);const scene=scenesRef.current.find(item=>item.id===id);return scene?savePatch(id,{title:scene.title,content:scene.content,summary:scene.summary,goal:scene.goal,conflict:scene.conflict,outcome:scene.outcome,location:scene.location,status:scene.status,povCharacterId:scene.povCharacterId}):true}
  async function enable(){onSaveStateChange("saving");const r=await fetch("/api/scenes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({chapterId,initialize:true})});if(!r.ok){onSaveStateChange("error");setError("Scene structure could not be enabled.");return}const data=await r.json();setScenes(data.scenes||[]);setActiveId(data.scenes?.[0]?.id||"");onChapterContentChange(data.aggregateContent||chapterContent);onAggregateSaved(data.aggregateContent||chapterContent);onSaveStateChange("saved")}
  async function add(){if(active)await flushScene(active.id);onSaveStateChange("saving");const r=await fetch("/api/scenes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({chapterId,afterSceneId:active?.id||null})});if(!r.ok){onSaveStateChange("error");setError("A new scene could not be added.");return}const data=await r.json(),next=(data.scenes||[]) as SceneRecord[];setScenes(next);const currentIndex=next.findIndex(scene=>scene.id===active?.id);setActiveId(next[Math.min(next.length-1,currentIndex+1)]?.id||next.at(-1)?.id||"");onChapterContentChange(data.aggregateContent);onAggregateSaved(data.aggregateContent);onSaveStateChange("saved")}
  async function split(beforeHtml:string,afterHtml:string){if(!active)return;const timer=timers.current.get(active.id);if(timer){clearTimeout(timer);timers.current.delete(active.id)}onSaveStateChange("saving");const r=await fetch(`/api/scenes/${active.id}/split`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({beforeHtml,afterHtml})});if(!r.ok){onSaveStateChange("error");setError("The scene could not be split.");return}const data=await r.json();setScenes(data.scenes||[]);setActiveId(data.createdId);onChapterContentChange(data.aggregateContent);onAggregateSaved(data.aggregateContent);onSaveStateChange("saved")}
  async function remove(){if(!active||ordered.length<=1)return;if(!confirm(`Delete “${active.title||`Scene ${activeIndex+1}`}”? The scene text will be permanently removed.`))return;await flushScene(active.id);const r=await fetch(`/api/scenes/${active.id}`,{method:"DELETE"});const data=await r.json().catch(()=>({error:"Scene could not be deleted."}));if(!r.ok){setError(data.error||"Scene could not be deleted.");return}const next=(data.scenes||[]) as SceneRecord[];setScenes(next);setActiveId(next[Math.max(0,activeIndex-1)]?.id||next[0]?.id||"");onChapterContentChange(data.aggregateContent);onAggregateSaved(data.aggregateContent);onSaveStateChange("saved")}
  async function disable(){if(!confirm("Remove scene structure from this chapter? The scene text will be kept and joined with visible scene breaks."))return;flushPending();const r=await fetch(`/api/chapters/${chapterId}/scenes/disable`,{method:"POST"});const data=await r.json().catch(()=>({error:"Scene structure could not be removed."}));if(!r.ok){setError(data.error||"Scene structure could not be removed.");return}setScenes([]);setActiveId("");onChapterContentChange(data.aggregateContent);onAggregateSaved(data.aggregateContent);onSaveStateChange("saved")}
  async function reorder(dragId:string,targetId:string,after:boolean){if(dragId===targetId)return;flushPending();const previous=[...ordered],rest=ordered.filter(scene=>scene.id!==dragId),moving=ordered.find(scene=>scene.id===dragId);if(!moving)return;const target=rest.findIndex(scene=>scene.id===targetId);if(target<0)return;rest.splice(target+(after?1:0),0,moving);const next=rest.map((scene,position)=>({...scene,position}));preview(next);setDragging(null);setDrop(null);const r=await fetch("/api/scenes/reorder",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({chapterId,sceneIds:next.map(scene=>scene.id)})});if(!r.ok){preview(previous);setError("Scene order could not be saved.");return}const data=await r.json();setScenes(data.scenes||next);onChapterContentChange(data.aggregateContent);onAggregateSaved(data.aggregateContent)}

  if(loading)return <div className="scene-loading">Loading scene structure…</div>;
  if(!scenes.length)return <><div className="scene-enable"><div><small>OPTIONAL SCENES</small><strong>Break this chapter into scenes</strong><span>Your existing manuscript becomes Scene 1. Then place the cursor where Scene 2 begins and use <b>✂ Scene</b>.</span></div><button onClick={enable}>Organise into scenes</button></div>{error&&<p className="scene-error">{error}</p>}<RichEditor value={chapterContent} novelId={novelId} onChange={onChapterContentChange} onCreateLinkedNote={onCreateLinkedNote} focusAnchorId={focusAnchorId} onAnchorClick={onAnchorClick}/></>;

  return <div className="scene-workspace">
    {!focus&&<div className="scene-strip">{ordered.map((scene,index)=><button draggable key={scene.id} className={`${scene.id===active?.id?"active":""} ${dragging===scene.id?"dragging":""} ${drop?.id===scene.id?(drop.after?"drop-after":"drop-before"):""}`} onClick={async()=>{if(active&&active.id!==scene.id)await flushScene(active.id);setActiveId(scene.id)}} onDragStart={e=>{setDragging(scene.id);e.dataTransfer.effectAllowed="move";e.dataTransfer.setData("text/plain",scene.id)}} onDragEnd={()=>{setDragging(null);setDrop(null)}} onDragOver={e=>{if(!dragging||dragging===scene.id)return;e.preventDefault();const box=e.currentTarget.getBoundingClientRect();setDrop({id:scene.id,after:e.clientX>box.left+box.width/2})}} onDrop={e=>{e.preventDefault();if(dragging)reorder(dragging,scene.id,drop?.id===scene.id?drop.after:false)}}><small>SCENE {index+1}</small><strong>{scene.title||`Scene ${index+1}`}</strong></button>)}<button className="scene-add" onClick={add}>＋ Scene</button></div>}
    {error&&<button className="scene-error" onClick={()=>setError("")}>{error} ×</button>}
    {!focus&&active&&<><div className="scene-heading"><div><small>SCENE {activeIndex+1} OF {ordered.length}</small><input value={active.title} placeholder={`Scene ${activeIndex+1}`} onChange={e=>edit({title:e.target.value})}/></div><span>{sceneWords.toLocaleString()} words</span></div><details className="scene-details"><summary>Scene details</summary><div className="scene-meta-grid"><label><span>POV character</span><select value={active.povCharacterId??""} onChange={e=>edit({povCharacterId:e.target.value||null},true)}><option value="">Not set</option>{characters.map(character=><option key={character.id} value={character.id}>{character.name}</option>)}</select></label><label><span>Location</span><input value={active.location} placeholder="Where does this scene happen?" onChange={e=>edit({location:e.target.value})}/></label><label><span>Status</span><select value={active.status} onChange={e=>edit({status:e.target.value},true)}><option value="DRAFT">Draft</option><option value="REVISE">Revise</option><option value="DONE">Done</option></select></label><label className="scene-meta-wide"><span>Summary</span><textarea value={active.summary} onChange={e=>edit({summary:e.target.value})}/></label><label><span>Goal</span><textarea value={active.goal} onChange={e=>edit({goal:e.target.value})}/></label><label><span>Conflict</span><textarea value={active.conflict} onChange={e=>edit({conflict:e.target.value})}/></label><label><span>Outcome</span><textarea value={active.outcome} onChange={e=>edit({outcome:e.target.value})}/></label></div></details></>}
    {active&&<RichEditor key={active.id} value={active.content} novelId={novelId} onChange={content=>edit({content})} onCreateLinkedNote={onCreateLinkedNote} focusAnchorId={focusAnchorId} onAnchorClick={onAnchorClick} onSplitScene={split}/>}
    {!focus&&activeIndex<ordered.length-1&&<div className="scene-break-preview" aria-label="Scene break">* * *</div>}
    {!focus&&<div className="scene-footer-actions"><button onClick={disable}>Remove scene structure</button><button className="danger" disabled={ordered.length<=1} onClick={remove}>Delete current scene</button></div>}
  </div>;
}
