"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import RichEditor,{plainText} from "./RichEditor";
import {combineSceneContents} from "@/lib/scenes";
import type {StoryReference} from "@/lib/story-reference";

export type SceneRecord={id:string;chapterId:string;povCharacterId:string|null;title:string;content:string;summary:string;goal:string;conflict:string;outcome:string;location:string;status:string;position:number};
type CharacterOption={id:string;name:string};
type SaveState="saved"|"saving"|"error";

export default function SceneEditor({chapterId,chapterContent,novelId,focus,onChapterContentChange,onAggregateSaved,onSaveStateChange,onCreateLinkedNote,focusAnchorId,onAnchorClick,storyReferences,referencesEnabled,onToggleReferences}:{chapterId:string;chapterContent:string;novelId:string;focus:boolean;onChapterContentChange:(content:string)=>void;onAggregateSaved:(content:string)=>void;onSaveStateChange:(state:SaveState)=>void;onCreateLinkedNote?:(quote:string,anchorId:string)=>Promise<boolean>;focusAnchorId?:string|null;onAnchorClick?:(anchorId:string)=>void;storyReferences:StoryReference[];referencesEnabled:boolean;onToggleReferences:()=>void}){
  const [scenes,setScenes]=useState<SceneRecord[]>([]),[characters,setCharacters]=useState<CharacterOption[]>([]),[loading,setLoading]=useState(true),[activeId,setActiveId]=useState(""),[dragging,setDragging]=useState<string|null>(null),[drop,setDrop]=useState<{id:string;after:boolean}|null>(null),[error,setError]=useState("");
  const timers=useRef(new Map<string,ReturnType<typeof setTimeout>>()),scenesRef=useRef<SceneRecord[]>([]),sceneRefs=useRef(new Map<string,HTMLElement>());
  useEffect(()=>{scenesRef.current=scenes},[scenes]);
  useEffect(()=>{let live=true;setLoading(true);setError("");fetch(`/api/scenes?chapterId=${chapterId}`,{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(data=>{if(!live)return;const next=(data.scenes||[]) as SceneRecord[];setScenes(next);setCharacters(data.characters||[]);setActiveId(next[0]?.id||"");setLoading(false)}).catch(()=>{if(live){setLoading(false);setError("Scenes could not be loaded.")}});return()=>{live=false;void flushPending(true)}},[chapterId]);

  const ordered=useMemo(()=>[...scenes].sort((a,b)=>a.position-b.position),[scenes]),active=ordered.find(scene=>scene.id===activeId)??ordered[0],activeIndex=Math.max(0,ordered.findIndex(scene=>scene.id===active?.id));
  useEffect(()=>{if(!focusAnchorId)return;const scene=scenes.find(item=>item.content.includes(focusAnchorId));if(!scene)return;setActiveId(scene.id);requestAnimationFrame(()=>sceneRefs.current.get(scene.id)?.scrollIntoView({behavior:"smooth",block:"start"}))},[focusAnchorId,scenes]);

  function wordCount(content:string){const text=plainText(content).trim();return text?text.split(/\s+/).length:0}
  function preview(next:SceneRecord[]){setScenes(next);onChapterContentChange(combineSceneContents([...next].sort((a,b)=>a.position-b.position).map(scene=>scene.content)))}
  async function savePatch(id:string,patch:Partial<SceneRecord>,keepalive=false){onSaveStateChange("saving");try{const r=await fetch(`/api/scenes/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(patch),keepalive});if(!r.ok)throw new Error();const data=await r.json();if(data.scenes)setScenes(data.scenes);if(typeof data.aggregateContent==="string"){onChapterContentChange(data.aggregateContent);onAggregateSaved(data.aggregateContent)}onSaveStateChange("saved");return true}catch{onSaveStateChange("error");setError("Scene changes could not be saved.");return false}}
  function schedulePatch(id:string,patch:Partial<SceneRecord>){const old=timers.current.get(id);if(old)clearTimeout(old);onSaveStateChange("saving");timers.current.set(id,setTimeout(()=>{timers.current.delete(id);void savePatch(id,patch)},650))}
  function editScene(id:string,patch:Partial<SceneRecord>,immediate=false){const next=scenes.map(scene=>scene.id===id?{...scene,...patch}:scene);preview(next);if(immediate)void savePatch(id,patch);else schedulePatch(id,patch)}
  async function flushPending(keepalive=false){const pending:Promise<boolean>[]=[];for(const [id,timer] of timers.current){clearTimeout(timer);const scene=scenesRef.current.find(item=>item.id===id);if(scene)pending.push(savePatch(id,{title:scene.title,content:scene.content,summary:scene.summary,goal:scene.goal,conflict:scene.conflict,outcome:scene.outcome,location:scene.location,status:scene.status,povCharacterId:scene.povCharacterId},keepalive))}timers.current.clear();return Promise.all(pending)}
  async function flushScene(id:string){const timer=timers.current.get(id);if(!timer)return true;clearTimeout(timer);timers.current.delete(id);const scene=scenesRef.current.find(item=>item.id===id);return scene?savePatch(id,{title:scene.title,content:scene.content,summary:scene.summary,goal:scene.goal,conflict:scene.conflict,outcome:scene.outcome,location:scene.location,status:scene.status,povCharacterId:scene.povCharacterId}):true}
  function scrollToScene(id:string,behavior:"smooth"|"auto"="smooth"){setActiveId(id);requestAnimationFrame(()=>sceneRefs.current.get(id)?.scrollIntoView({behavior,block:"start"}))}
  async function enable(){onSaveStateChange("saving");const r=await fetch("/api/scenes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({chapterId,initialize:true})});if(!r.ok){onSaveStateChange("error");setError("Scene structure could not be enabled.");return}const data=await r.json();setScenes(data.scenes||[]);setActiveId(data.scenes?.[0]?.id||"");onChapterContentChange(data.aggregateContent||chapterContent);onAggregateSaved(data.aggregateContent||chapterContent);onSaveStateChange("saved")}
  async function add(){if(active&&!await flushScene(active.id))return;onSaveStateChange("saving");const r=await fetch("/api/scenes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({chapterId,afterSceneId:active?.id||null})});if(!r.ok){onSaveStateChange("error");setError("A new scene could not be added.");return}const data=await r.json(),next=(data.scenes||[]) as SceneRecord[];setScenes(next);const currentIndex=next.findIndex(scene=>scene.id===active?.id),target=next[Math.min(next.length-1,currentIndex+1)]??next.at(-1);if(target){setActiveId(target.id);requestAnimationFrame(()=>sceneRefs.current.get(target.id)?.scrollIntoView({behavior:"smooth",block:"start"}))}onChapterContentChange(data.aggregateContent);onAggregateSaved(data.aggregateContent);onSaveStateChange("saved")}
  async function split(id:string,beforeHtml:string,afterHtml:string){const timer=timers.current.get(id);if(timer){clearTimeout(timer);timers.current.delete(id)}onSaveStateChange("saving");const r=await fetch(`/api/scenes/${id}/split`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({beforeHtml,afterHtml})});if(!r.ok){onSaveStateChange("error");setError("The scene could not be split.");return}const data=await r.json();setScenes(data.scenes||[]);setActiveId(data.createdId);onChapterContentChange(data.aggregateContent);onAggregateSaved(data.aggregateContent);onSaveStateChange("saved");requestAnimationFrame(()=>sceneRefs.current.get(data.createdId)?.scrollIntoView({behavior:"smooth",block:"start"}))}
  async function remove(){if(!active||ordered.length<=1)return;if(!confirm(`Delete “${active.title||`Scene ${activeIndex+1}`}”? The scene text will be permanently removed.`))return;if(!await flushScene(active.id))return;const r=await fetch(`/api/scenes/${active.id}`,{method:"DELETE"});const data=await r.json().catch(()=>({error:"Scene could not be deleted."}));if(!r.ok){setError(data.error||"Scene could not be deleted.");return}const next=(data.scenes||[]) as SceneRecord[];setScenes(next);const target=next[Math.max(0,activeIndex-1)]??next[0];setActiveId(target?.id||"");onChapterContentChange(data.aggregateContent);onAggregateSaved(data.aggregateContent);onSaveStateChange("saved");if(target)requestAnimationFrame(()=>sceneRefs.current.get(target.id)?.scrollIntoView({behavior:"smooth",block:"start"}))}
  async function disable(){if(!confirm("Remove scene structure from this chapter? The scene text will be kept and joined with visible scene breaks."))return;await flushPending();const r=await fetch(`/api/chapters/${chapterId}/scenes/disable`,{method:"POST"});const data=await r.json().catch(()=>({error:"Scene structure could not be removed."}));if(!r.ok){setError(data.error||"Scene structure could not be removed.");return}setScenes([]);setActiveId("");onChapterContentChange(data.aggregateContent);onAggregateSaved(data.aggregateContent);onSaveStateChange("saved")}
  async function reorder(dragId:string,targetId:string,after:boolean){if(dragId===targetId)return;await flushPending();const previous=[...ordered],rest=ordered.filter(scene=>scene.id!==dragId),moving=ordered.find(scene=>scene.id===dragId);if(!moving)return;const target=rest.findIndex(scene=>scene.id===targetId);if(target<0)return;rest.splice(target+(after?1:0),0,moving);const next=rest.map((scene,position)=>({...scene,position}));preview(next);setDragging(null);setDrop(null);onSaveStateChange("saving");const r=await fetch("/api/scenes/reorder",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({chapterId,sceneIds:next.map(scene=>scene.id)})});if(!r.ok){preview(previous);setError("Scene order could not be saved.");onSaveStateChange("error");return}const data=await r.json();setScenes(data.scenes||next);onChapterContentChange(data.aggregateContent);onAggregateSaved(data.aggregateContent);onSaveStateChange("saved")}

  if(loading)return <div className="scene-loading">Loading scene structure…</div>;
  if(!scenes.length)return <><div className="scene-enable"><div><small>OPTIONAL SCENES</small><strong>Break this chapter into scenes</strong><span>Your existing manuscript becomes Scene 1. Then place the cursor where Scene 2 begins and use <b>✂ Scene</b>.</span></div><button onClick={enable}>Organise into scenes</button></div>{error&&<p className="scene-error">{error}</p>}<RichEditor value={chapterContent} novelId={novelId} onChange={onChapterContentChange} onCreateLinkedNote={onCreateLinkedNote} focusAnchorId={focusAnchorId} onAnchorClick={onAnchorClick} storyReferences={storyReferences} referencesEnabled={referencesEnabled} onToggleReferences={onToggleReferences}/></>;

  return <div className={`scene-workspace scene-workspace-continuous${focus?" focus-scenes":""}`}>
    {!focus&&<div className="scene-strip">{ordered.map((scene,index)=><button draggable key={scene.id} className={`${scene.id===active?.id?"active":""} ${dragging===scene.id?"dragging":""} ${drop?.id===scene.id?(drop.after?"drop-after":"drop-before"):""}`} onClick={()=>scrollToScene(scene.id)} onDragStart={e=>{setDragging(scene.id);e.dataTransfer.effectAllowed="move";e.dataTransfer.setData("text/plain",scene.id)}} onDragEnd={()=>{setDragging(null);setDrop(null)}} onDragOver={e=>{if(!dragging||dragging===scene.id)return;e.preventDefault();const box=e.currentTarget.getBoundingClientRect();setDrop({id:scene.id,after:e.clientX>box.left+box.width/2})}} onDrop={e=>{e.preventDefault();if(dragging)void reorder(dragging,scene.id,drop?.id===scene.id?drop.after:false)}}><small>SCENE {index+1}</small><strong>{scene.title||`Scene ${index+1}`}</strong></button>)}<button className="scene-add" onClick={add}>＋ Scene</button></div>}
    {error&&<button className="scene-error" onClick={()=>setError("")}>{error} ×</button>}
    <div className="scene-continuous-list">
      {ordered.map((scene,index)=>{const isActive=scene.id===active?.id;return <section key={scene.id} ref={el=>{if(el)sceneRefs.current.set(scene.id,el);else sceneRefs.current.delete(scene.id)}} className={`scene-continuous-item${isActive?" active":""}`} onFocusCapture={()=>setActiveId(scene.id)}>
        {index>0&&<div className="scene-divider" aria-label={`Scene ${index+1} divider`}><i/><span>SCENE {index+1}{scene.title?` · ${scene.title}`:""}</span><i/></div>}
        {!focus&&<div className="scene-heading scene-inline-heading"><div><small>SCENE {index+1} OF {ordered.length}</small><input value={scene.title} placeholder={`Scene ${index+1}`} onFocus={()=>setActiveId(scene.id)} onChange={e=>editScene(scene.id,{title:e.target.value})}/></div><span>{wordCount(scene.content).toLocaleString()} words</span></div>}
        {!focus&&isActive&&<details className="scene-details"><summary>Scene details</summary><div className="scene-meta-grid"><label><span>POV character</span><select value={scene.povCharacterId??""} onChange={e=>editScene(scene.id,{povCharacterId:e.target.value||null},true)}><option value="">Not set</option>{characters.map(character=><option key={character.id} value={character.id}>{character.name}</option>)}</select></label><label><span>Location</span><input value={scene.location} placeholder="Where does this scene happen?" onChange={e=>editScene(scene.id,{location:e.target.value})}/></label><label><span>Status</span><select value={scene.status} onChange={e=>editScene(scene.id,{status:e.target.value},true)}><option value="DRAFT">Draft</option><option value="REVISE">Revise</option><option value="DONE">Done</option></select></label><label className="scene-meta-wide"><span>Summary</span><textarea value={scene.summary} onChange={e=>editScene(scene.id,{summary:e.target.value})}/></label><label><span>Goal</span><textarea value={scene.goal} onChange={e=>editScene(scene.id,{goal:e.target.value})}/></label><label><span>Conflict</span><textarea value={scene.conflict} onChange={e=>editScene(scene.id,{conflict:e.target.value})}/></label><label><span>Outcome</span><textarea value={scene.outcome} onChange={e=>editScene(scene.id,{outcome:e.target.value})}/></label></div></details>}
        <RichEditor value={scene.content} novelId={novelId} onChange={content=>editScene(scene.id,{content})} onCreateLinkedNote={onCreateLinkedNote} focusAnchorId={focusAnchorId} onAnchorClick={onAnchorClick} onSplitScene={(beforeHtml,afterHtml)=>split(scene.id,beforeHtml,afterHtml)} storyReferences={storyReferences} referencesEnabled={referencesEnabled} onToggleReferences={onToggleReferences} showToolbar={isActive} referenceHighlightKey={scene.id} continuousSegment onEditorFocus={()=>setActiveId(scene.id)}/>
      </section>})}
    </div>
    {!focus&&<div className="scene-footer-actions"><button onClick={disable}>Remove scene structure</button><button className="danger" disabled={ordered.length<=1} onClick={remove}>Delete current scene</button></div>}
  </div>;
}
